<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for the Physical Sciences and Engineering - 7&nbsp; Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-nonlinear.html" rel="next">
<link href="./06-propagation.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

</head><body class="nav-sidebar docked">$$
\def\reals{\mathbb{R}}
\def\card#1{| #1 |}
\def\mean{\overline}
\def\evProb#1{\operatorname{Prob}(\mbox{#1})}
\def\Prob{\operatorname{Prob}}
\def\tand{\operatorname{and}}
\def\tor{\operatorname{or}}
\def\tnot{\operatorname{not}}
\def\E{{\operatorname E}}
\def\Var{\operatorname{Var}}
\def\SD{\operatorname{SD}}
\def\union{\cup}
\def\intersect{\cap}
\def\Unif{\mathsf{Unif}}
\def\Beta{\mathsf{Beta}}
\def\Rayleigh{\mathsf{Rayleigh}}
\def\Exp{\mathsf{Exp}}
\def\Norm{\mathsf{Norm}}
\def\Tri{\mathsf{Tri}}
\def\Gamm{\mathsf{Gamma}}
\def\Pois{\mathsf{Pois}}
\def\Binom{\mathsf{Binom}}
\def\Weibull{\mathsf{Weibull}}
\def\Tdist{\mathsf{T}}
\def\Fdist{\mathsf{F}}
\def\Chisq{\mathsf{Chisq}}
\def\boolval#1{[\![ #1 ]\!]}
\def\simiid{\stackrel{\mathrm{iid}{\sim}}}

\def\sfrac#1#2{{#1}/{#2}}
\def\PartialFrac#1#2{\frac{\partial #1}{\partial #2}}
\def\Partial#1#2{\frac{\partial}{\partial #2} #1}

\def\myindex#1{\relax}
$$

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="book.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Models</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for the Physical Sciences and Engineering</a> 
        <div class="sidebar-tools-main">
    <a href="./Pruim-Stat-for-Phys-Sci-and-Engr.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-chap0.html" class="sidebar-item-text sidebar-link">Where do numbers come from?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-graphical.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Graphical Summaries of Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-numerical.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Numerical Summaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-transformations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transformation and Combinations of Random Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-propagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propagation of Uncertainty</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-simple-linear.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-nonlinear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Beyond Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hypothesis-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-more-examples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More Examples</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-simple-linear-regression-model" id="toc-the-simple-linear-regression-model" class="nav-link active" data-scroll-target="#the-simple-linear-regression-model"><span class="toc-section-number">7.1</span>  The Simple Linear Regression Model</a></li>
  <li><a href="#fitting-the-simple-linear-model" id="toc-fitting-the-simple-linear-model" class="nav-link" data-scroll-target="#fitting-the-simple-linear-model"><span class="toc-section-number">7.2</span>  Fitting the Simple Linear Model</a>
  <ul class="collapse">
  <li><a href="#the-least-squares-method" id="toc-the-least-squares-method" class="nav-link" data-scroll-target="#the-least-squares-method"><span class="toc-section-number">7.2.1</span>  The Least Squares Method</a></li>
  <li><a href="#an-example-estimating-osa" id="toc-an-example-estimating-osa" class="nav-link" data-scroll-target="#an-example-estimating-osa"><span class="toc-section-number">7.2.2</span>  An Example: Estimating OSA</a></li>
  <li><a href="#explanatory-and-response-variables-matter" id="toc-explanatory-and-response-variables-matter" class="nav-link" data-scroll-target="#explanatory-and-response-variables-matter"><span class="toc-section-number">7.2.3</span>  Explanatory and Response Variables Matter</a></li>
  </ul></li>
  <li><a href="#estimating-the-response" id="toc-estimating-the-response" class="nav-link" data-scroll-target="#estimating-the-response"><span class="toc-section-number">7.3</span>  Estimating the Response</a>
  <ul class="collapse">
  <li><a href="#cautionary-note-dont-extrapolate" id="toc-cautionary-note-dont-extrapolate" class="nav-link" data-scroll-target="#cautionary-note-dont-extrapolate"><span class="toc-section-number">7.3.1</span>  Cautionary Note: Don’t Extrapolate!</a></li>
  </ul></li>
  <li><a href="#parameter-estimates" id="toc-parameter-estimates" class="nav-link" data-scroll-target="#parameter-estimates"><span class="toc-section-number">7.4</span>  Parameter Estimates</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-coefficients" id="toc-interpreting-the-coefficients" class="nav-link" data-scroll-target="#interpreting-the-coefficients"><span class="toc-section-number">7.4.1</span>  Interpreting the Coefficients</a></li>
  <li><a href="#estimating-sigma" id="toc-estimating-sigma" class="nav-link" data-scroll-target="#estimating-sigma"><span class="toc-section-number">7.4.2</span>  Estimating <span class="math inline">\(\sigma\)</span></a></li>
  </ul></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions"><span class="toc-section-number">7.5</span>  Checking Assumptions</a>
  <ul class="collapse">
  <li><a href="#what-have-we-assumed" id="toc-what-have-we-assumed" class="nav-link" data-scroll-target="#what-have-we-assumed"><span class="toc-section-number">7.5.1</span>  What have we assumed?</a></li>
  <li><a href="#dont-fit-a-line-if-a-line-doesnt-fit" id="toc-dont-fit-a-line-if-a-line-doesnt-fit" class="nav-link" data-scroll-target="#dont-fit-a-line-if-a-line-doesnt-fit"><span class="toc-section-number">7.5.2</span>  Don’t Fit a Line If a Line Doesn’t Fit</a></li>
  <li><a href="#checking-the-residuals" id="toc-checking-the-residuals" class="nav-link" data-scroll-target="#checking-the-residuals"><span class="toc-section-number">7.5.3</span>  Checking the Residuals</a></li>
  <li><a href="#outliers-in-regression" id="toc-outliers-in-regression" class="nav-link" data-scroll-target="#outliers-in-regression"><span class="toc-section-number">7.5.4</span>  Outliers in Regression</a></li>
  </ul></li>
  <li><a href="#how-good-are-our-estimates" id="toc-how-good-are-our-estimates" class="nav-link" data-scroll-target="#how-good-are-our-estimates"><span class="toc-section-number">7.6</span>  How Good Are Our Estimates?</a>
  <ul class="collapse">
  <li><a href="#estimating-the-betas" id="toc-estimating-the-betas" class="nav-link" data-scroll-target="#estimating-the-betas"><span class="toc-section-number">7.6.1</span>  Estimating the <span class="math inline">\(\beta\)</span>s</a></li>
  <li><a href="#confidence-and-prediction-intervals-for-the-response-value" id="toc-confidence-and-prediction-intervals-for-the-response-value" class="nav-link" data-scroll-target="#confidence-and-prediction-intervals-for-the-response-value"><span class="toc-section-number">7.6.2</span>  Confidence and Prediction Intervals for the Response Value</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In <a href="06-propagation.html"><span>Chapter&nbsp;6</span></a> we learned how to estimate one quantity based on its (known) relationship to other quantities. For example, we estimated the number of dimes in a sack of dimes from our estimates of the weight of the dimes and the average weight of a dime.</p>
<p>In this chapter we will explore how to use data to determine the relationship among two or more variables when this relationship is not known in advance. The general framework we will use is</p>
<p><span class="math display">\[
Y = f(x_1, x_2, \dots, x_k) + \varepsilon
\]</span></p>
<div class="itemize">
<ul>
<li><p><span class="math inline">\(Y\)</span> is the <strong>response</strong> variable that we are trying to estimate from <span class="math inline">\(k\)</span> <strong>explanatory</strong> or <strong>predictor</strong> variables <span class="math inline">\(x_1, x_2, \dots, x_k\)</span>.</p></li>
<li><p>The relationship between the explanatory variables and the response variables is described by a function <span class="math inline">\(f\)</span>.</p></li>
<li><p>The relationship described by <span class="math inline">\(f\)</span> need not be a perfect fit. The <strong>error</strong> term in the model, <span class="math inline">\(\varepsilon\)</span>, describes how individual responses differ from the value given by <span class="math inline">\(f\)</span>.</p>
<p>We will model <span class="math inline">\(\varepsilon\)</span> with a distribution – typically a distribution with a mean of 0 – so another way to think about this model is the for a given values of the predictors, the values of <span class="math inline">\(Y\)</span> have a distribution. The mean of this distribution is specified by <span class="math inline">\(f\)</span> and the shape by <span class="math inline">\(\varepsilon\)</span>.</p></li>
</ul>
</div>
<!-- end itemize -->
<section id="the-simple-linear-regression-model" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-simple-linear-regression-model"><span class="header-section-number">7.1</span> The Simple Linear Regression Model</h2>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x + \varepsilon  \qquad \mbox{where $\varepsilon \sim \Norm(0,\sigma)$.}
\]</span></p>
<p>In other words:</p>
<div class="enumerate">
<ol type="1">
<li><p>The mean response for a given predictor value <span class="math inline">\(x\)</span> is given by a linear formula <span class="math display">\[
\mbox{mean response} = \beta_0 + \beta_1 x
\]</span></p>
<p>This can also be written as <span class="math display">\[
\E(Y \mid X = x) = \beta_0 + \beta_1 x
\]</span></p></li>
<li><p>The distribution of all responses for a given predictor value <span class="math inline">\(x\)</span> is normal.</p></li>
<li><p>The standard deviation of the responses is the same for each predictor value.</p></li>
</ol>
</div>
<!-- end enumerate -->
<p>Furthermore, in this model the values of <span class="math inline">\(\varepsilon\)</span> are independent.</p>
<p>There are many different things we might want to do with a linear model, for example:</p>
<div class="itemize">
<ul>
<li>Estimate the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</li>
<li>Estimate the value <span class="math inline">\(Y\)</span> associated with a particular value of <span class="math inline">\(x\)</span>.</li>
<li>Say something about how well a line fits the data.</li>
</ul>
</div>
<!-- end itemize -->
</section>
<section id="fitting-the-simple-linear-model" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="fitting-the-simple-linear-model"><span class="header-section-number">7.2</span> Fitting the Simple Linear Model</h2>
<section id="the-least-squares-method" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="the-least-squares-method"><span class="header-section-number">7.2.1</span> The Least Squares Method</h3>
<p>We want to determine the best fitting line to the data. The usual method is the method of least squares<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, which chooses the line that has the <em>smallest possible sum of squares of residuals</em>, where residuals are defined by</p>
<p><span class="math display">\[
\mbox{residual} = \mbox{observed} - \mbox{predicted}
\]</span></p>
<div class="example">
<p>Consider the following small data set.</p>
<div class="columns">
<div class="columnn" width="45%">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>SomeData <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">5</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>SomeData</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["x"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["y"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"1"},{"1":"2","2":"4"},{"1":"4","2":"3"},{"1":"5","2":"6"},{"1":"6","2":"5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div><div class="columnn" width="45%">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( y <span class="sc">~</span> x, <span class="at">data =</span> SomeData) <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>), <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="432"></p>
</div>
</div>
</div>
</div>
<div class="enumerate">
<ol>
<li>Add a line to the plot that “fits the data well”. Don’t do any calculations, just add the line.</li>
<li>Now estimate the residuals for each point relative to your line</li>
<li>Compute the sum of the squared residuals, <span class="math inline">\(SSE\)</span>.</li>
<li>Estimate the slope and intercept of your line.</li>
</ol>
</div>
<!-- end enumerate -->
<div style="page-break-after: always;"></div>
<p>For example, suppose we we select a line that passes through <span class="math inline">\((1,2)\)</span> and <span class="math inline">\((6,6)\)</span>. the equation for this line is <span class="math inline">\(y = 1.2 + 0.8 x\)</span>, and it looks like a pretty good fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>( <span class="fl">1.2</span> <span class="sc">+</span> <span class="fl">0.8</span> <span class="sc">*</span> x <span class="sc">~</span> x)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(y <span class="sc">~</span> x, <span class="at">data =</span> SomeData) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>( <span class="fu">f</span>(x) <span class="sc">~</span> x, <span class="at">col =</span> <span class="st">"gray50"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>The residuals for this function are</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>resids <span class="ot">&lt;-</span> <span class="fu">with</span>(SomeData, y <span class="sc">-</span> <span class="fu">f</span>(x)) ; resids </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.0  1.2 -1.4  0.8 -1.0</code></pre>
</div>
</div>
<p>and <span class="math inline">\(SSE\)</span> is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(resids<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.04</code></pre>
</div>
</div>
<p>The following plot provides a way to visualize the sum of the squared residuals (SSE).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>If your line is a good fit, then <span class="math inline">\(SSE\)</span> will be small.<br>
The best fitting line will have the smallest possible <span class="math inline">\(SSE\)</span>.<br>
The <code>lm()</code> function will find this best fitting line for us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( y <span class="sc">~</span> x, <span class="at">data =</span> SomeData ); model1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = SomeData)

Coefficients:
(Intercept)            x  
     1.1628       0.7326  </code></pre>
</div>
</div>
<p>This says that the equation of the best fit line is <span class="math display">\[
\hat y = 1.1627907 + 0.7325581 x
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(y <span class="sc">~</span> x, <span class="at">data =</span> SomeData) <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using the `size` aesthietic with geom_line was deprecated in ggplot2 3.4.0.
ℹ Please use the `linewidth` aesthetic instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>We can compute <span class="math inline">\(SSE\)</span> using the <code>resid()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span> (<span class="fu">resid</span>(model1)<span class="sc">^</span><span class="dv">2</span>); SSE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.569767</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>As we see, this is a better fit than our first attempt – at least according to the least squares criterion. It will better than <em>any</em> other attempt – it is the least squares regression line.</p>
</div>
<!-- end example -->
<p>For a line with equation <span class="math inline">\(y = \hat\beta_0 + \hat\beta_1 x\)</span>, the residuals are <span class="math display">\[
e_i = y_i - (\hat\beta_0 + \hat\beta_1 x)
\]</span> and the sum of the squares of the residuals is <span class="math display">\[
SSE = \sum e_i^2  = \sum (y_i - (\hat\beta_0 + \hat\beta_1 x) )^2
\]</span> Simple calculus (which we won’t do here) allows us to compute the best <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> possible.<br>
These best values define the least squares regression line. We always compute these values using software, but it is good to note that the least squares line satisfies two very nice properties.</p>
<div class="enumerate">
<ol>
<li>The point <span class="math inline">\((\mean x, \mean y)\)</span> is on the line.</li>
</ol>
<p>This means that <span class="math inline">\(\mean y = \hat\beta_0 + \hat\beta_1 \mean x\)</span> (and <span class="math inline">\(\hat\beta_0 = \mean y - \hat\beta_1 \mean x\)</span>) #. The slope of the line is <span class="math inline">\(\displaystyle b = r \frac{s_y}{s_x}\)</span> where <span class="math inline">\(r\)</span> is the <strong>correlation coefficient</strong>: <!--  --> <span class="math display">\[
r = \frac{1}{n-1} \sum \frac{ x_i - \mean x }{s_x} \cdot \frac{ y_i - \mean y }{s_y}
\]</span></p>
</div>
<!-- end enumerate -->
<p>Since we have a point and the slope, it is easy to compute the equation for the line if we know <span class="math inline">\(\mean x\)</span>, <span class="math inline">\(s_x\)</span>, <span class="math inline">\(\mean y\)</span>, <span class="math inline">\(s_y\)</span>, and <span class="math inline">\(r\)</span>.</p>
</section>
<section id="an-example-estimating-osa" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="an-example-estimating-osa"><span class="header-section-number">7.2.2</span> An Example: Estimating OSA</h3>
<div class="example">
<p>In a study of eye strain caused by visual display terminals, researchers wanted to be able to estimate ocular surface area (OSA) from palpebral fissure (the horizontal width of the eye opening in cm) because palpebral fissue is easier to measure than OSA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Eyes <span class="ot">&lt;-</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read.table</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://rpruim.github.io/Engineering-Statistics/data/PalpebralFissure.txt"</span>, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Eyes, <span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["palpebral"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["OSA"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.40","2":"1.02","_rn_":"1"},{"1":"0.42","2":"1.21","_rn_":"2"},{"1":"0.48","2":"0.88","_rn_":"3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>x.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>( <span class="sc">~</span> palpebral, <span class="at">data =</span> Eyes)  </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>y.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>( <span class="sc">~</span> OSA, <span class="at">data =</span> Eyes)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>s_x <span class="ot">&lt;-</span> <span class="fu">sd</span>( <span class="sc">~</span> palpebral, <span class="at">data =</span> Eyes)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>s_y <span class="ot">&lt;-</span> <span class="fu">sd</span>( <span class="sc">~</span> OSA, <span class="at">data =</span> Eyes)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>( palpebral <span class="sc">~</span> OSA, <span class="at">data =</span> Eyes)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>( <span class="at">x.bar =</span> x.bar, <span class="at">y.bar =</span> y.bar, <span class="at">s_x =</span> s_x, <span class="at">s_y =</span> s_y, <span class="at">r =</span> r )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    x.bar     y.bar       s_x       s_y         r 
1.0513333 2.8403333 0.3798160 1.2083374 0.9681245 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>slope <span class="ot">&lt;-</span> r <span class="sc">*</span> s_y <span class="sc">/</span> s_x</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>intercept <span class="ot">&lt;-</span> y.bar <span class="sc">-</span> slope <span class="sc">*</span> x.bar</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">intercept =</span> intercept, <span class="at">slope =</span> slope)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> intercept      slope 
-0.3977389  3.0799672 </code></pre>
</div>
</div>
</div>
<!-- end example -->
<p>Fortunately, statistical software packages do all this work for us, so the calculations of the preceding example don’t need to be done in practice.</p>
<div class="example">
<p>In a study of eye strain caused by visual display terminals, researchers wanted to be able to estimate ocular surface area (OSA) from palpebral fissure (the horizontal width of the eye opening in cm) because palpebral fissue is easier to measure than OSA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>osa.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(OSA <span class="sc">~</span> palpebral, <span class="at">data =</span> Eyes) </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>osa.model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = OSA ~ palpebral, data = Eyes)

Coefficients:
(Intercept)    palpebral  
    -0.3977       3.0800  </code></pre>
</div>
</div>
<p><code>lm()</code> stands for linear model. The default output includes the estimates of the coefficients (<span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span>) based on the data. If that is the only information we want, then we can use</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(osa.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   palpebral 
 -0.3977389   3.0799672 </code></pre>
</div>
</div>
<p>This means that the equation of the least squares regression line is <span class="math display">\[
\hat y = -0.398 + 3.08 x
\]</span></p>
<p>We use <span class="math inline">\(\hat y\)</span> to indicate that this is not an observed value of the response variable but an estimated value (based on the linear equation given).</p>
<p>R&nbsp;can add a regression line to our scatter plot if we ask it to.</p>
<div class="center">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( OSA <span class="sc">~</span> palpebral, <span class="at">data =</span> Eyes) <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/osa-scatter-1.png" class="img-fluid" width="432"></p>
</div>
</div>
</div>
<!-- end center -->
<p>We see that the line does run roughly “through the middle” of the data but that there is some variability above and below the line.</p>
</div>
<!-- end example -->
</section>
<section id="explanatory-and-response-variables-matter" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="explanatory-and-response-variables-matter"><span class="header-section-number">7.2.3</span> Explanatory and Response Variables Matter</h3>
<p>It is important that the explanatory variable be the “<code>x</code>” variable and the response variable be the “<code>y</code>” variable when doing regression. If we reverse the roles of <code>OSA</code> and <code>palpebral</code> we do not get the same model. This is because the residuals are measured vertically (in the <span class="math inline">\(y\)</span> direction).</p>
</section>
</section>
<section id="estimating-the-response" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="estimating-the-response"><span class="header-section-number">7.3</span> Estimating the Response</h2>
<p>We can use our least squares regression line to estimate the value of the response variable from the value of the explanatory variable.</p>
<div class="example">
<p>If the palpebral width is 1.2 cm, then we would estimate OSA to be</p>
<p><span class="math display">\[
\hat{`osa`} =
-0.398 + 3.08 \cdot 1.2
= 3.298
\]</span></p>
<p>R&nbsp;can automate this for us too. The <code>makeFun()</code> function will create a function from our model.<br>
If we input a palpebral measurement into this function, the function will return the estimated OSA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>estimated.osa <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(osa.model)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">estimated.osa</span>(<span class="fl">1.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
3.298222 </code></pre>
</div>
</div>
<p>As it turns out, the 17th measurement in our data set had a <code>palpebral</code> measurement of 1.2 cm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Eyes[<span class="dv">17</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["palpebral"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["OSA"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"1.2","2":"3.76","_rn_":"17"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The corresponding OSA of 3.76 means that the residual for this observation is <span class="math display">\[
\mbox{observed} - \mbox{predicted} = 3.76 - 3.2982218 =
0.4617782  
\]</span></p>
</div>
<!-- end example -->
<section id="cautionary-note-dont-extrapolate" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="cautionary-note-dont-extrapolate"><span class="header-section-number">7.3.1</span> Cautionary Note: Don’t Extrapolate!</h3>
<p>While it often makes sense to generate model predictions corresponding to x-values <em>within</em> the range of values measured in the dataset, it is dangerous to <em>extrapolate</em> and make predictions for values <em>outside</em> the range included in the dataset. To assume that the linear relationship observed in the dataset holds for explanatory variable values outside the observed range, we would need a convincing, valid justification, which is usually not available. If we extrapolate anyway, we risk generating erroneous or even nonsense predictions. The problem generally gets worse as we stray further from the observed range of explanatory-variable values.</p>
</section>
</section>
<section id="parameter-estimates" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="parameter-estimates"><span class="header-section-number">7.4</span> Parameter Estimates</h2>
<section id="interpreting-the-coefficients" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="interpreting-the-coefficients"><span class="header-section-number">7.4.1</span> Interpreting the Coefficients</h3>
<p>The coefficients of the linear model tell us how to construct the linear function that we use to estimate response values, but they can be interesting in their own right as well.</p>
<p>The intercept <span class="math inline">\(\beta_0\)</span> is the mean response value when the explanatory variable is 0. This may or may not be interesting. Often <span class="math inline">\(\beta_0\)</span> is not interesting because we are not interested in the value of the response variable when the predictor is 0. (That might not even be a possible value for the predictor.) Furthermore, if we do not collect data with values of the explanatory variable near 0, then we will be extrapolating from our data when we talk about the intercept. (Extrapolating is dangerous because we can’t really be sure that the relationships we’ve uncovered with our model really hold for variable values outside the range we measured.)</p>
<p>The estimate for <span class="math inline">\(\beta_1\)</span>, on the other hand, is nearly always of interest. The slope coefficient <span class="math inline">\(\beta_1\)</span> tells us how quickly the response variable changes per unit change in the predictor. This is an interesting value in many more situations. Furthermore, when <span class="math inline">\(\beta_1 = 0\)</span>, then our model does not depend on the predictor at all. So if we construct a confidence interval for <span class="math inline">\(\beta_1\)</span>, and it contains 0, then we do <em>not</em> have sufficient evidence to be convinced that our predictor is of any use in predicting the response.</p>
</section>
<section id="estimating-sigma" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="estimating-sigma"><span class="header-section-number">7.4.2</span> Estimating <span class="math inline">\(\sigma\)</span></h3>
<p>There is one more parameter in our model that we have been mostly ignoring so far: <span class="math inline">\(\sigma\)</span> (or equivalently <span class="math inline">\(\sigma^2\)</span>). This is the parameter that describes how tightly things should cluster around the regression line. We can estimate <span class="math inline">\(\sigma^2\)</span> from our residuals:</p>
<p><span class="math display">\[
\begin{aligned}
\hat\sigma^2 &amp; = MSE = \frac{ \sum_i e_i^2 }{ n -2 }
\\
\hat\sigma &amp; = RMSE = \sqrt{MSE} = \sqrt{\frac{ \sum_i e_i^2 }{ n -2 } }
\end{aligned}
\]</span></p>
<p>The acronyms <span class="math inline">\(MSE\)</span> and <span class="math inline">\(RMSE\)</span> stand for <strong>Mean Squared Error</strong> and <strong>Root Mean Squared Error</strong>. The numerator in these expressions is the sum of the squares of the residuals <span class="math display">\[
SSE = \sum_i e_i^2 \;.
\]</span> This is precisely the quantity that we were minimizing to get our least squares fit. <span class="math display">\[
MSE = \frac{SSE}{DFE}
\]</span> where <span class="math inline">\(DFE = n-2\)</span> is the <strong>degrees of freedom</strong> associated with the estimation of <span class="math inline">\(\sigma^2\)</span> in a simple linear model. We lose two degrees of freedom when we estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, just like we lost 1 degree of freedom when we had to estimate <span class="math inline">\(\mu\)</span> in order to compute a sample variance.</p>
<p><span class="math inline">\(RMSE = \sqrt{MSE}\)</span> is listed in the summary output for the linear model as the <strong>residual standard error</strong> because it is the estimated standard deviation of the error terms in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(osa.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = OSA ~ palpebral, data = Eyes)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.60942 -0.19875 -0.01902  0.21727  0.66378 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.3977     0.1680  -2.367   0.0251 *  
palpebral     3.0800     0.1506  20.453   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.308 on 28 degrees of freedom
Multiple R-squared:  0.9373,    Adjusted R-squared:  0.935 
F-statistic: 418.3 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We will learn about other parts of this summary output shortly. Much is known about the estimator <span class="math inline">\(\sigma^2\)</span>, including</p>
<div class="itemize">
<ul>
<li><span class="math inline">\(\hat \sigma^2\)</span> is unbiased (on average it is <span class="math inline">\(\sigma^2\)</span>), and</li>
<li>the sampling distribution is related to a Chi-Squared distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.<br>
(Chi-Squared distributions are a special case of Gamma distributions.) More specifically, <span class="math display">\[
     \frac{SSE}{\sigma^2} = \frac{(n - 2) \hat \sigma^2}{\sigma^2} \sim \Chisq(n-2) \;.
\]</span></li>
</ul>
</div>
<!-- end itemize -->
</section>
</section>
<section id="checking-assumptions" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="checking-assumptions"><span class="header-section-number">7.5</span> Checking Assumptions</h2>
<section id="what-have-we-assumed" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="what-have-we-assumed"><span class="header-section-number">7.5.1</span> What have we assumed?</h3>
<p>In fitting a linear regression model, we have assumed:</p>
<div class="itemize">
<ul>
<li>A linear relationship between the explanatory and response variables</li>
<li>The errors (<span class="math inline">\(\epsilon\)</span>) are Normally distributed</li>
<li>Independence of the errors (in particular, no correlation over time between successive errors for data points collected over time)</li>
<li>Homoscedasticity of the errors – this means that the variance (spread) of the errors is constant over time, and over the full range of explanatory and predictor variables</li>
</ul>
</div>
<!-- end itemize -->
</section>
<section id="dont-fit-a-line-if-a-line-doesnt-fit" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="dont-fit-a-line-if-a-line-doesnt-fit"><span class="header-section-number">7.5.2</span> Don’t Fit a Line If a Line Doesn’t Fit</h3>
<p>The least squares method can be used to fit a line to any data – even if a line is not a useful representation of the relationship between the variables. When doing regression we should always look at the data to see if a line is a good fit. If it is not, then the simple linear model is not a good choice and we should look for some other model that does a better job of describing the relationship between our two variables.</p>
</section>
<section id="checking-the-residuals" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="checking-the-residuals"><span class="header-section-number">7.5.3</span> Checking the Residuals</h3>
<p>We look at the residuals (not just the data scatter plot) because some of our assumptions refer specifically to them. Also, often, it is easier to assess the linear fit by looking at a plot of the residuals than by looking at the natural scatter plot, because on the scale of the residuals, violations of our assumptions are easier to see.</p>
<p>So, to verify that our linear regression assumptions are sensible, we can examine the model residuals. Residuals should be checked to see that their distribution looks approximately normal and that thier standard deviation (the spread of the residuals) remains consistent across the range of our data (and across time).</p>
<p>In addition, especially if the data were collected over time (measurements made in order during an experiment; data points collected at a series of time points), it is important to verify that the residuals are <em>independent</em> of one another over time. To look for this problem, we can look at a scatter plot of the residuals as a function of time, and suspect a problem if we see series of very large, or very small, residuals all in a row. Another plot that can help us look for non-independence in the residuals is a plot of the autocorrelation function (ACF), obtained using the <code>acf()</code> function in R. This function computes and plots the correlation coefficient R for the residuals at various “lags”. For example, the correlation coefficient for lag 1 is the correlation coefficient between each residual (corresponding to the <em>i</em>th datapoint) and the preceding one (the <em>i-1</em>th data point). Lag 2 is between the <em>i</em>th and <em>i-2</em>th data point, and so on. If the residuals are not independent, then these coefficients will have large absolute values. (Note: the “lag 0” coefficient measures the correlation of the <em>i</em>th residual with itself, so it is always 1. This does NOT indicate any problem with the linear regression model.)</p>
<p>In general, we might want to check the following plots of the residuals:</p>
<div class="itemize">
<ul>
<li>Residuals as a function of “fitted values”, or model predictions for the x-values obseved in the actual data set.</li>
<li>Residuals as a function of the observed values of the explanatory variable (from the actual data set).</li>
<li>Normal quantile-quantile plot of the residuals (note: in Chapter 4, we made these by hand for any distribution; you may also use the shortcut function qqmath() as illustrated below, to make them for the Normal distribution.)</li>
<li>Residuals as a function of time (if you know the order in which they were collected, or if the explanatory variable is a time-related one).</li>
<li>Residual autocorrelation function plot (if the data points were collected over time, or if the explanatory variable is a time-related one).</li>
</ul>
</div>
<!-- end itemize -->
<p>For all the scatter plots, we want to make sure the residuals “look random” – the extent of the spread of the residuals should not vary with time or x or y (``trumpet”-shaped plot). If there is a pattern, it suggests a problem with the homoscedasticity assumption. There should not be long runs of similar residuals, especially over time; if there are, it suggests non-independence of the residuals. There should also be no apparent trends in the plot, linear or non-linear; if there are, it suggests that the relationship between the predictor and response variables was not linear. In an autocorrelation plot, the correlation coefficients (except for lag 0) should not be too large, far exceeding the dotted guide-lines on the plot; if they are, there is probably a problem with the independence assumption.</p>
<div class="example">
<p>Returning to our OSA data, we can obtain the residuals using the <code>resid()</code> function and plot them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>osa.hat <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(osa.model)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">osa.hat</span>(Eyes<span class="sc">$</span>palpebral)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( <span class="fu">resid</span>(osa.model) <span class="sc">~</span> preds, <span class="at">data =</span> Eyes,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span><span class="st">"Residuals versus fitted values"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(osa.model),  <span class="at">data =</span> Eyes, <span class="at">title =</span> <span class="st">"Normal QQ plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(osa.model) <span class="sc">~</span> palpebral, <span class="at">data =</span> Eyes,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Residuals versus explanatory variable"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid" width="432"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">resid</span>(osa.model), <span class="at">ylab =</span> <span class="st">"Residual ACF"</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/acfplot-1.png" class="img-fluid" width="576"></p>
</div>
</div>
</div>
<!-- end example -->
<p>If the assumptions of the model are correct, there should be no distinct patterns to these scatter plots of the residuals, and the normal-quantile plot should be roughly linear (since the model says that differences between observed responses and the true linear fit should be random noise following a normal distribution with constant standard deviation).</p>
<p>In this case things look pretty good.</p>
<p>We can save ourselves a little typing if we create these plots using <code>plot()</code> or <code>mplot()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(osa.model, <span class="at">w =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="432"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>The “standardized” residuals are the residuals that have been adjusted to have an expected variance (and hence also standard deviation) of 1. Roughly, they are the residuals divided by <span class="math inline">\(\hat \sigma\)</span>, but there is an additional adjustment that is made as well. This gives us a kind of unitless version of the residual and the normal-quantile plot using standardized residuals does a better job of indicating whether the normality assumption is compatibly with the data. (Remember, the normality assumption is about the <em>errors</em> not the residuals. The standardized residuals should behave roughly like a normal distribution if the errors are normally distributed.) Typically the shape of the normal-quantile plot made with raw residuals and the one made with standarized residuals will be very similar.</p>
</section>
<section id="outliers-in-regression" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="outliers-in-regression"><span class="header-section-number">7.5.4</span> Outliers in Regression</h3>
<p>Outliers can be very influential in regression, especially in small data sets, and especially if they occur for extreme values of the explanatory variable. Outliers cannot be removed just because we don’t like them, but they should be explored to see what is going on (data entry error? special case? etc.)</p>
<p>Some researchers will do “leave-one-out” analysis, or “leave some out” analysis where they refit the regression with each data point left out once. If the regression summary changes very little when we do this, this means that the regression line is summarizing information that is shared among all the points relatively equally. But if removing one or a small number of values makes a dramatic change, then we know that that point is exerting a lot of influence over the resulting analysis (a cause for caution).</p>
<p>This kind of analysis can be very helpful, especially if you have one or several large potential outliers in your data set, but in this class, we will not generally do it as a matter of course (it’s not a required part of model assessment for coursework).</p>
</section>
</section>
<section id="how-good-are-our-estimates" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="how-good-are-our-estimates"><span class="header-section-number">7.6</span> How Good Are Our Estimates?</h2>
<p>Assuming our diagnostics indicate that fitting a linear model is reasonable for our data, our next question is <em>How good are our estimates?</em> Notice that there are several things we have estimated:</p>
<div class="itemize">
<ul>
<li>The intercept coefficient <span class="math inline">\(\beta_0\)</span> [estimate: <span class="math inline">\(\hat \beta_0\)</span>]</li>
<li>The slope coefficient <span class="math inline">\(\beta_1\)</span> [estimate: <span class="math inline">\(\hat \beta_1\)</span>]</li>
<li>Values of <span class="math inline">\(y\)</span> for given values of <span class="math inline">\(x\)</span>. [estimate: <span class="math inline">\(\hat y = \hat \beta_0 + \hat \beta_1 x\)</span>]</li>
</ul>
</div>
<!-- end itemize -->
<p>We would like to be able to compute uncertainties and confidence intervals for these. Fortunately, R&nbsp;makes this straightforward.</p>
<section id="estimating-the-betas" class="level3" data-number="7.6.1">
<h3 data-number="7.6.1" class="anchored" data-anchor-id="estimating-the-betas"><span class="header-section-number">7.6.1</span> Estimating the <span class="math inline">\(\beta\)</span>s</h3>
<div class="example">
<p><strong>Q.</strong> Returning to the OSA data, compute standard uncertainties and 95% confidence intervals for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p><strong>A.</strong> The <code>summary()</code> function provides additional information about the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(osa.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = OSA ~ palpebral, data = Eyes)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.60942 -0.19875 -0.01902  0.21727  0.66378 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.3977     0.1680  -2.367   0.0251 *  
palpebral     3.0800     0.1506  20.453   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.308 on 28 degrees of freedom
Multiple R-squared:  0.9373,    Adjusted R-squared:  0.935 
F-statistic: 418.3 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<pre><code>We don't know what to do with all of the information displayed here, but we can see
some familiar things in the coefficient table.  </code></pre>
<p>If we only want the coefficients part of the summary output we can get that using</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(osa.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) -0.3977389  0.1680090 -2.367367 2.506081e-02
palpebral    3.0799672  0.1505882 20.452918 2.252825e-18</code></pre>
</div>
</div>
<p>From this we see the estimates (<span class="math inline">\(\hat \beta\)</span>’s) displayed again. Next to each of those is a standard error. That is the standard uncertainty for these estimates. So we could report our estimated coefficients as</p>
<p><span class="math display">\[
    \beta_0: -0.40 \pm  --&gt;
        0.17
    \qquad
    \beta_1: 3.08 \pm  
        0.15
\]</span></p>
<p>A confidence interval can be computed using <span class="math display">\[
    \hat\beta_i \pm t_* SE_{\beta_i}
\]</span> because</p>
<div class="itemize">
<ul>
<li>the sampling distribution for <span class="math inline">\(\hat \beta_i\)</span> is normal,</li>
<li>the sampling distribution for <span class="math inline">\(\hat \beta_i\)</span> is unbiased (the mean is <span class="math inline">\(\beta_i\)</span>), and</li>
<li>the standard deviation of the sampling distribution depends on <span class="math inline">\(\sigma\)</span> (and some other things), but</li>
<li>we don’t know <span class="math inline">\(\sigma\)</span>, so we have to estimate it using <span class="math inline">\(RMSE = \sqrt{MSE}\)</span>.</li>
</ul>
</div>
<!-- end itemize -->
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>t.star <span class="ot">&lt;-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">28</span>); t.star    <span class="co"># n-2 degrees of freedom for simple linear regression</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.048407</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>t.star <span class="sc">*</span> <span class="fl">0.151</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3093095</code></pre>
</div>
</div>
<pre><code>So a 95% confidence interval for $\beta_1$ is </code></pre>
<p><span class="math display">\[
    3.08 \pm 0.31
\]</span> The degrees of freedom used are <span class="math inline">\(DFE = n-2\)</span>, the same as used in the estimate of <span class="math inline">\(\sigma^2\)</span>. (We are using a t-distribution instead of a normal distribution because we don’t know <span class="math inline">\(\sigma\)</span>. The degrees of freedom are those associated with using <span class="math inline">\(RMSE = \sqrt{MSE}\)</span> as our estimate for <span class="math inline">\(\sigma\)</span>.)</p>
<pre><code>R\ can compute confidence intervals for both parameters using the function
`confint()`:</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(osa.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) -0.7418897 -0.05358811
palpebral    2.7715014  3.38843310</code></pre>
</div>
</div>
<p>A 68% confidence interval should have a margin of error of approximately 1 standard uncertainty:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(osa.model, <span class="at">level =</span> <span class="fl">0.68</span>, <span class="st">"palpebral"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              16 %     84 %
palpebral 2.927507 3.232428</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">3.2325</span> <span class="sc">-</span> <span class="fl">2.9275</span>) <span class="sc">/</span> <span class="dv">2</span>   <span class="co"># margin of error</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1525</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(osa.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) -0.3977389  0.1680090 -2.367367 2.506081e-02
palpebral    3.0799672  0.1505882 20.452918 2.252825e-18</code></pre>
</div>
</div>
</div>
<!-- end example -->
</section>
<section id="confidence-and-prediction-intervals-for-the-response-value" class="level3" data-number="7.6.2">
<h3 data-number="7.6.2" class="anchored" data-anchor-id="confidence-and-prediction-intervals-for-the-response-value"><span class="header-section-number">7.6.2</span> Confidence and Prediction Intervals for the Response Value</h3>
<p>We can also create interval estimates for the response. R&nbsp;will compute this if we simply ask:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>estimated.osa <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(osa.model)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">estimated.osa</span>(<span class="fl">1.2</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 3.298222 3.174238 3.422206</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estimated.osa</span>(<span class="fl">0.8</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 2.066235 1.927384 2.205086</code></pre>
</div>
</div>
<p>These intervals are confidence intervals for the <em>mean</em> response. Sometimes it is desirable to create an interval that will have a 95% chance of containing a new <em>observation</em> – that is, including the anticipated error as well as the mean response. These intervals are called <strong>prediction intervals</strong> to distinguish them from the usual confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>estimated.osa <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(osa.model)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">estimated.osa</span>(<span class="fl">1.2</span>, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 3.298222 2.655228 3.941216</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estimated.osa</span>(<span class="fl">0.8</span>, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr     upr
1 2.066235 1.420209 2.71226</code></pre>
</div>
</div>
<p>Prediction intervals are typically much wider than confidence intervals.<br>
We have to “cast a wider net” to create an interval that is highly likely to contain a new observation (which might be quite a bit above or below the mean).</p>
<p>The widths of both types of intervals depend on the value(s) of the explanatory variable(s) from which we are making the estimate. Estimates are more precise near the mean of the predictor variable and become less precise as we move away from there. Extrapolation beyond the observed data range is both less precise, and risky, because we don’t have data to know whether the linear pattern seen in the data extends into that region.</p>
<p>The plot below illustrates both confidence (dotted) and prediction (dashed) intervals. Notice how most of the dots are within the prediction bands, but not within the confidence bands.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(OSA <span class="sc">~</span> palpebral, <span class="at">data =</span> Eyes) <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>(<span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>(<span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using the `size` aesthietic with geom_ribbon was deprecated in ggplot2 3.4.0.
ℹ Please use the `linewidth` aesthetic instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid"></p>
</div>
</div>
<section id="a-caution-regarding-prediction-intervals" class="level4" data-number="7.6.2.1">
<h4 data-number="7.6.2.1" class="anchored" data-anchor-id="a-caution-regarding-prediction-intervals"><span class="header-section-number">7.6.2.1</span> A Caution Regarding Prediction Intervals</h4>
<p>Prediction intervals are much more sensitive to the normality assumption than confidence intervals are because the Central Limit Theorem does not help when we are thinking about individual observations (essentially samples of size 1). So if the true distribution of errors is not really normal, then the prediction intervals we compute using the normality assumption will not be accurate.</p>
<div id="exr-rainfall" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.1 </strong></span><strong>Rainfall</strong></p>
<p>Use the output below to answer some questions about rainfall volume and runoff volume (both in <span class="math inline">\(m^3\)</span>) for a particular stretch of a Texas highway.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = runoff ~ rainfall, data = TexasHighway)

Residuals:
   Min     1Q Median     3Q    Max 
-8.279 -4.424  1.205  3.145  8.261 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.12830    2.36778  -0.477    0.642    
rainfall     0.82697    0.03652  22.642  7.9e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.24 on 13 degrees of freedom
Multiple R-squared:  0.9753,    Adjusted R-squared:  0.9734 
F-statistic: 512.7 on 1 and 13 DF,  p-value: 7.896e-12</code></pre>
</div>
</div>
<div class="enumerate">
<ol>
<li>How many times were rainfall and runoff recorded?</li>
<li>What is the equation for the least squares regression line?</li>
<li>Report the slope together with its standard uncertainty.</li>
<li>Give a 95% confidence interval for the slope of this line.</li>
<li>What does this slope tell you about runoff on this stretch of highway?</li>
<li>What is <span class="math inline">\(\hat\sigma\)</span>?</li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<div class="enumerate">
<ol>
<li>The residual degrees of freedom is <span class="math inline">\(13\)</span>, so there were <span class="math inline">\(13 + 2 = 15\)</span> observations.</li>
<li><span class="math inline">\(`runoff` = -1 + 0.83 \cdot `rainfall`\)</span></li>
<li><span class="math inline">\(0.83 \pm 0.04\)</span></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>( rain.model, <span class="st">"rainfall"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 %    97.5 %
rainfall 0.7480677 0.9058786</code></pre>
</div>
</div>
<pre><code>We can compute this from the information displayed:</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>t.star <span class="ot">&lt;-</span> <span class="fu">qt</span>( .<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">13</span> ) <span class="co"># 13 df listed for residual standard error</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>t.star</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.160369</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fl">0.0365</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>ME <span class="ot">&lt;-</span> t.star <span class="sc">*</span> SE; SE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0365</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.8270</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> ME  <span class="co"># CI as an interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7481465 0.9058535</code></pre>
</div>
</div>
<p>We should round this using our rounding rules (treating the margin of error like an uncertainty). #. The slope tells us how much additional run-off there is per additional amount of rain that falls. Since both are in the same units (<span class="math inline">\(m^3\)</span>) and since the intercept is essentially 0, we can interpret this slope as a proportion. Roughly 83% of the rain water is being measured as runoff. #. <span class="math inline">\(5.24\)</span></p>
</div>
<!-- end enumerate -->
</div>
<!-- end solution -->
<div id="exr-kids-feet" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.2 </strong></span><strong>Kids’ feet</strong></p>
<p>The <code>KidsFeet</code> data set contains variables giving the widths and lengths of feet of some grade school kids.</p>
<ol type="1">
<li>Perform our usual diagnostics to see whether there are any reasons to be concerned about using a simple linear model in this situation.</li>
<li>Based on this data, what estimate would you give for the width of a Billy’s foot if Billy’s foot is 24 cm long?<br>
(Use a 95% confidence level.)</li>
<li>Based on this data, what estimate would you give for the average width of a kids’ feet that 24 cm long? (Use a 95% confidence level.)</li>
</ol>
</div>
<!-- end problem -->
<div class="mysolution">
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>foot.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(width <span class="sc">~</span> length, <span class="at">data =</span> KidsFeet)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(foot.model, <span class="at">w =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(foot.model, <span class="at">w =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Our diagnostics look pretty good. The residuals look randomly distributed with similar amounts of variability throughout the plot. The normal-quantile plot is nearly linear.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(foot.model)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(<span class="dv">24</span>, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 8.813022 7.996604 9.629441</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(<span class="dv">24</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 8.813022 8.665894 8.960151</code></pre>
</div>
</div>
<p>We can’t estimate Billy’s foot width very accurately (between 8.0 and 9.6 cm), but we can estimate the average foot width for all kids with a foot length of 24 cm more accurately (between 8.67 and 8.96 cm).</p>
</div>
<!-- end solution -->
<div id="exr-bike-space" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.3 </strong></span><strong>Space for bicycles</strong></p>
<p>Some traffic engineers were interested to study interactions between bicycle and automobile traffic. One part of the study involved comparing the amount of “available space” for a bicyclist (distance in feet from bicycle to centerline of the roadway) and “separation distance” (the average distance between cyclists and passing car, also measured in feet, determined by averaging based on photography over an extend period of time). Data were collected at 10 different sites with bicycle lanes. The data are available in the <code>ex12.21</code> data set in the <strong><code>Devore7</code></strong> package.</p>
<ol type="1">
<li>Write out an equation for the least squares regression line for predicting separation distance from available space.</li>
<li>Give an estimate (with uncertainty) for the slope and interpret it.</li>
<li>A new bicycle lane is planned for a street that has 15 feet of available space. Give an interval estimate for the separation distance on this new street. Should you use a confidence interval or a prediction interval? Why?</li>
<li>Give a scenario in which you would use the other kind of interval.</li>
</ol>
</div>
<!-- end problem -->
<div class="mysolution">
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>bike.model <span class="ot">&lt;-</span> <span class="fu">lm</span>( distance <span class="sc">~</span> space, <span class="at">data =</span> Devore7<span class="sc">::</span>ex12<span class="fl">.21</span> )</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(bike.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) -2.1824715 1.05668813 -2.065388 7.274847e-02
space        0.6603419 0.06747931  9.785841 9.974851e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(bike.model)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>( <span class="dv">15</span>, <span class="at">interval =</span> <span class="st">"prediction"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 7.722656 6.313278 9.132035</code></pre>
</div>
</div>
<p>We would use a confidence interval to estimate the average separation distance for all streets with 15 feet of available space.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>( <span class="dv">15</span>, <span class="at">interval =</span> <span class="st">"confidence"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 7.722656 7.293168 8.152145</code></pre>
</div>
</div>
</div>
<!-- end solution -->
<div id="exr-biometrics" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.4 </strong></span><strong>Biometrics</strong></p>
<p>Select only the non-diabetic men from the <code>pheno</code> data set using</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastR2)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>Men <span class="ot">&lt;-</span> Pheno <span class="sc">|&gt;</span> <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"M"</span> <span class="sc">&amp;</span> t2d<span class="sc">==</span><span class="st">"control"</span>)  <span class="co"># note the double == and quotes here</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Men, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["id"],"name":[1],"type":["int"],"align":["right"]},{"label":["t2d"],"name":[2],"type":["fct"],"align":["left"]},{"label":["bmi"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["sex"],"name":[4],"type":["fct"],"align":["left"]},{"label":["age"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["smoker"],"name":[6],"type":["fct"],"align":["left"]},{"label":["chol"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["waist"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["weight"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["height"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["whr"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["sbp"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["dbp"],"name":[13],"type":["dbl"],"align":["right"]}],"data":[{"1":"1012","2":"control","3":"30.47048","4":"M","5":"53.86161","6":"former","7":"5.02","8":"104","9":"94.6","10":"176.2","11":"0.9327354","12":"143","13":"89","_rn_":"1"},{"1":"1110","2":"control","3":"26.75386","4":"M","5":"68.07944","6":"never","7":"5.63","8":"99","9":"81.0","10":"174.0","11":"0.9252336","12":"162","13":"91","_rn_":"2"},{"1":"1146","2":"control","3":"NA","4":"M","5":"62.14521","6":"NA","7":"NA","8":"NA","9":"NA","10":"NA","11":"NA","12":"NA","13":"NA","_rn_":"3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>This data set contains some phenotype information for subjects in a large genetics study. You can find out more about the data set with</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>?pheno</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="enumerate">
<ol>
<li><p>Using this data, fit a linear model that can be used to predict weight from height. What is the equation of the least squares regression line?</p></li>
<li><p>Give a 95% confidence interval for the slope of this regression and interpret it in context. (Hint: what are the units?)</p></li>
<li><p>Give a 95% confidence interval for the mean weight of all non-diabetic men who are 6 feet tall.</p>
<p>Note the heights are in cm and the weights are in kg, so you will need to convert units to use inches and pounds. (2.54 cm per inch, 2.2 pounds per kg)</p></li>
<li><p>Perform regression diagnostics. Is there any reason to be concerned about this analysis?</p></li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<div class="enumerate">
<ol>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>( weight <span class="sc">~</span> height, <span class="at">data =</span> Men )</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) -69.6988584 12.14450332 -5.739128 1.551023e-08
height        0.8706793  0.06994051 12.448856 1.277243e-31</code></pre>
</div>
</div>
<!--  So the equation is  -->
<!-- %$$ -->
<!-- <!--           `weight` =  -->
<p>–&gt; <!-- %          -70 +  --> <!-- <!--           0.87 \cdot `height` --> –&gt; <!-- %$$ --></p>
<ol>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can ask for just the parameter we want, if we like</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model, <span class="at">parm =</span> <span class="st">"height"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           2.5 %   97.5 %
height 0.7333052 1.008053</code></pre>
</div>
</div>
<p>The slope tells us how much the average weight (in kg) increases per cm of height.</p>
<ol>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(model)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co"># in kg</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(<span class="dv">6</span> <span class="sc">*</span> <span class="dv">12</span> <span class="sc">*</span> <span class="fl">2.54</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 89.53098 87.97557 91.08639</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># in pounds</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(<span class="dv">6</span> <span class="sc">*</span> <span class="dv">12</span> <span class="sc">*</span> <span class="fl">2.54</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">*</span> <span class="fl">2.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 196.9682 193.5463 200.3901</code></pre>
</div>
</div>
<ol>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(model) <span class="sc">~</span> <span class="fu">fitted</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-42-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>We could also have used</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(model, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(model, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-43-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>The residual plot looks fine. There is bit of a bend to the normal-quantile plot, indicating that the distribution of residuals is a bit skewed (to the right – the heaviest men are farther above the mean weight for their height than the lightest men are below).</p>
<p>In this particular case, a log transformation of the weights improves the residual distribution. There is still one man whose weight is quite high for his height, but otherwise things look quite good.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( <span class="fu">log</span>(weight) <span class="sc">~</span> height, <span class="at">data =</span> Men)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate   Std. Error  t value     Pr(&gt;|t|)
(Intercept) 2.5134829 0.1448876368 17.34781 2.145773e-54
height      0.0108067 0.0008344117 12.95128 8.626095e-34</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(model2) <span class="sc">~</span> <span class="fu">fitted</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-simple-linear_files/figure-html/unnamed-chunk-44-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>This model says that <span class="math display">\[
\log( `weight` )
    = 2.51 + 0.0108 \cdot `height`
\]</span> So <span class="math display">\[
`weight`  
= 12.3
        \cdot (1.011)^{`height`}
\]</span></p>
</div>
<!-- end enumerate -->
</div>
<!-- end solution -->
<div id="exr-anscombe" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.5 </strong></span><strong>Anscobe’s data</strong></p>
<p>The <code>anscombe</code> data set contains four pairs of explanatory (<code>x1</code>, <code>x2</code>, <code>x3</code>, and <code>x4</code>) and response (<code>y1</code>, <code>y2</code>, <code>y3</code>, and <code>y4</code>) variables. These data were constructed by Anscombe (<span class="citation" data-cites="Anscombe:1973:Graphs">Anscombe (<a href="references.html#ref-Anscombe:1973:Graphs" role="doc-biblioref">1973</a>)</span>).</p>
<div class="enumerate">
<ol type="1">
<li><p>For each of the four pairs, us R&nbsp;to fit a linear model and compare the results.<br>
Briefly describe what you notice looking at this output. (You do not have to submit the output itself – let’s save some paper.)</p>
<p>Use, for example,</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>    model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y1 <span class="sc">~</span> x1, <span class="at">data =</span> anscombe); <span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li><p>For each model, create a scatterplot that includes the regression line. (Make the plots fairly small and submit them.)</p></li>
<li><p>Comment on the results. Why do you think Anscombe invented these data?</p></li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<p>Anscombe’s data show that it is not sufficient to look only at the numerical summaries produced by regression software. His four data sets produce nearly identical output of and yet show very different fits. An inspection of the residuals (or even simple scatterplots) quickly reveals the various difficulties.</p>
</div>
<!-- end solution -->
<div id="exr-article" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.6 </strong></span><strong>Read and article</strong></p>
<p>Find an article from the engineering or science literature that uses a simple linear model and report the following information:</p>
<div class="enumerate">
<ol type="a">
<li>Print the first page of the article (with title and abstract) and write a full citation for the article on it. Staple this at the end of your assigment.</li>
<li>If the article is available online, provide a URL where it can be found. (You can write that on the printout of the first page of the article, too.)</li>
<li>How large was the data set used to fit the linear model? How do you know? (How did the authors communicate this information?)</li>
<li>What are the explanatory and response variables?</li>
<li>Did the paper give an equation for the least squares regression line (or the coefficients, from which you can determine the regression equation)? If so, report the equation</li>
<li>Did the paper show a scatter plot of the data? Was the regression line shown on the plot?</li>
<li>Did the paper provide confidence intervals or uncertainties for the coefficients in the model?</li>
<li>Did the paper show any diagnostic plots (normal-quantile, residuals plots, etc.)? If not, did the authors say anything in the text about checking that a linear model is appropriate in their situation?</li>
<li>What was the main conclusion of the analysis of the linear model?</li>
<li>If there is an indication that the data are available online, let me know where in case we want to use these data for an example.</li>
</ol>
</div>
<!-- end enumerate -->
<p>Google scholar might be a useful tool for locating an article, or a service like JSTOR (available through many academic libraries) also has a large number of scientific articles. Or you might ask an engineering or physics professor for an appropriate engineering journal to page through in the library. Since the chances are small that two students will find the same article if working independently, I expect to see lots of different articles used for this problem.</p>
<!-- If your article looks particularly interesting or contains statistical  -->
<!-- things that you don't understand but would like to understand, let me know, -->
<!-- and perhaps we can do something later in the semester with your article. -->
<!-- It's easiest to do this if you can give me a URL for locating the paper online. -->
</div>
<!-- end problem -->
<div id="exr-human-waste-in-japan" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 7.7 </strong></span><strong>Human waste in Japan</strong></p>
<p>High population density in Japan leads to many resource usage problems, including human waste removal. In a study of a new (in the 1990’s) copression machine for processing sewage sludge, researchers measures the moisture content of the compressed pellets (%) and the machines filtration rate (kg-DS/m/hr). You can load the data using</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(xmp12<span class="fl">.06</span>, <span class="at">package =</span> <span class="st">"Devore7"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="enumerate">
<ol type="a">
<li>What are the least squares estimates for the intercept and slope of a line that can be used to estimate the moisture content from the filtration rate? (Give them in our usual manner with both estimate and uncertainty.)</li>
<li>The first row of the data is</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(xmp12<span class="fl">.06</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["moistcon"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["filtrate"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"77.9","2":"125.3","_rn_":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Compute the residual for this observation.</p>
<ol start="3" type="a">
<li>What is <span class="math inline">\(\hat \sigma\)</span>, the estimated value of <span class="math inline">\(\sigma\)</span>?</li>
<li>Give a 95% confidence interval for the slope.</li>
<li>Give a 95% confidence interval for the mean moisture content when the filtration rate is 170 kg-DS/m/hr.</li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(xmp12<span class="fl">.06</span>, <span class="at">package =</span> <span class="st">"Devore7"</span>)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>sewage.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(moistcon <span class="sc">~</span> filtrate, <span class="at">data =</span> xmp12<span class="fl">.06</span>)</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="co"># a)</span></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(sewage.model))  <span class="co"># this includes standard errors; could also use summary() </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error    t value     Pr(&gt;|t|)
(Intercept) 72.95854697 0.697528488 104.595795 1.615724e-26
filtrate     0.04103377 0.004836781   8.483693 1.051720e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># b)</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">resid</span>(sewage.model)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1 
-0.2000784 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># c)</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(sewage.model)  <span class="co"># can also be read off of the summary() output</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6653314</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co"># d)</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(sewage.model)[<span class="dv">2</span>, , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %     97.5 %
filtrate 0.03087207 0.05119547</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># e) </span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>estimated.moisture <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(sewage.model)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="fu">estimated.moisture</span>(<span class="dv">170</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr     upr
1 79.93429 79.50398 80.3646</code></pre>
</div>
</div>
</div>
<!-- end solution -->


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Anscombe:1973:Graphs" class="csl-entry" role="doc-biblioentry">
Anscombe, F. J. 1973. <span>“Graphs in Statistical Analysis.”</span> <em>The American Statistician</em> 27 (1): 17.
</div>
</div>
</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>In this case, it turns out that the least squares and maximum likelihood methods produce exactly the same results.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-propagation.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propagation of Uncertainty</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-nonlinear.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Beyond Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>