<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for the Physical Sciences and Engineering - 8&nbsp; Beyond Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-hypothesis-testing.html" rel="next">
<link href="./07-simple-linear.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

</head><body class="nav-sidebar docked">$$
\def\reals{\mathbb{R}}
\def\card#1{| #1 |}
\def\mean{\overline}
\def\evProb#1{\operatorname{Prob}(\mbox{#1})}
\def\Prob{\operatorname{Prob}}
\def\tand{\operatorname{and}}
\def\tor{\operatorname{or}}
\def\tnot{\operatorname{not}}
\def\E{{\operatorname E}}
\def\Var{\operatorname{Var}}
\def\SD{\operatorname{SD}}
\def\union{\cup}
\def\intersect{\cap}
\def\Unif{\mathsf{Unif}}
\def\Beta{\mathsf{Beta}}
\def\Rayleigh{\mathsf{Rayleigh}}
\def\Exp{\mathsf{Exp}}
\def\Norm{\mathsf{Norm}}
\def\Tri{\mathsf{Tri}}
\def\Gamm{\mathsf{Gamma}}
\def\Pois{\mathsf{Pois}}
\def\Binom{\mathsf{Binom}}
\def\Weibull{\mathsf{Weibull}}
\def\Tdist{\mathsf{T}}
\def\Fdist{\mathsf{F}}
\def\Chisq{\mathsf{Chisq}}
\def\boolval#1{[\![ #1 ]\!]}
\def\simiid{\stackrel{\mathrm{iid}{\sim}}}

\def\sfrac#1#2{{#1}/{#2}}
\def\PartialFrac#1#2{\frac{\partial #1}{\partial #2}}
\def\Partial#1#2{\frac{\partial}{\partial #2} #1}

\def\myindex#1{\relax}
$$

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="book.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Beyond Linear Regression</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for the Physical Sciences and Engineering</a> 
        <div class="sidebar-tools-main">
    <a href="./Pruim-Stat-for-Phys-Sci-and-Engr.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-chap0.html" class="sidebar-item-text sidebar-link">Where do numbers come from?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-graphical.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Graphical Summaries of Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-numerical.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Numerical Summaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-transformations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transformation and Combinations of Random Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-propagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propagation of Uncertainty</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-simple-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-nonlinear.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Beyond Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hypothesis-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-more-examples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More Examples</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-big-is-your-r2" id="toc-how-big-is-your-r2" class="nav-link active" data-scroll-target="#how-big-is-your-r2"><span class="toc-section-number">8.1</span>  How big is your <span class="math inline">\(R^2\)</span>?</a></li>
  <li><a href="#violations-of-linear-regression-assumptions" id="toc-violations-of-linear-regression-assumptions" class="nav-link" data-scroll-target="#violations-of-linear-regression-assumptions"><span class="toc-section-number">8.2</span>  Violations of Linear Regression Assumptions</a></li>
  <li><a href="#non-normal-errors" id="toc-non-normal-errors" class="nav-link" data-scroll-target="#non-normal-errors"><span class="toc-section-number">8.3</span>  Non-Normal Errors</a></li>
  <li><a href="#non-independence-of-errors" id="toc-non-independence-of-errors" class="nav-link" data-scroll-target="#non-independence-of-errors"><span class="toc-section-number">8.4</span>  Non-Independence of Errors</a></li>
  <li><a href="#heteroskedasticity-non-constant-error-variance" id="toc-heteroskedasticity-non-constant-error-variance" class="nav-link" data-scroll-target="#heteroskedasticity-non-constant-error-variance"><span class="toc-section-number">8.5</span>  Heteroskedasticity (Non-constant Error Variance)</a></li>
  <li><a href="#non-linear-relationships" id="toc-non-linear-relationships" class="nav-link" data-scroll-target="#non-linear-relationships"><span class="toc-section-number">8.6</span>  Non-linear Relationships</a></li>
  <li><a href="#transformations-in-linear-regression" id="toc-transformations-in-linear-regression" class="nav-link" data-scroll-target="#transformations-in-linear-regression"><span class="toc-section-number">8.7</span>  Transformations in Linear Regression</a>
  <ul class="collapse">
  <li><a href="#reasons-for-using-transformations" id="toc-reasons-for-using-transformations" class="nav-link" data-scroll-target="#reasons-for-using-transformations"><span class="toc-section-number">8.7.1</span>  Reasons for Using Transformations</a></li>
  <li><a href="#three-important-laws" id="toc-three-important-laws" class="nav-link" data-scroll-target="#three-important-laws"><span class="toc-section-number">8.7.2</span>  Three Important Laws</a></li>
  <li><a href="#other-models-that-can-be-transformed-to-linear" id="toc-other-models-that-can-be-transformed-to-linear" class="nav-link" data-scroll-target="#other-models-that-can-be-transformed-to-linear"><span class="toc-section-number">8.7.3</span>  Other Models That Can Be Transformed to Linear</a></li>
  <li><a href="#sec-ladder-of-re-expression" id="toc-sec-ladder-of-re-expression" class="nav-link" data-scroll-target="#sec-ladder-of-re-expression"><span class="toc-section-number">8.7.4</span>  The Ladder of Re-expression</a></li>
  </ul></li>
  <li><a href="#nonlinear-least-squares" id="toc-nonlinear-least-squares" class="nav-link" data-scroll-target="#nonlinear-least-squares"><span class="toc-section-number">8.8</span>  Nonlinear Least Squares</a>
  <ul class="collapse">
  <li><a href="#choosing-between-linear-and-non-linear-models" id="toc-choosing-between-linear-and-non-linear-models" class="nav-link" data-scroll-target="#choosing-between-linear-and-non-linear-models"><span class="toc-section-number">8.8.1</span>  Choosing Between Linear and Non-linear Models</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">8.9</span>  Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Beyond Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="how-big-is-your-r2" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="how-big-is-your-r2"><span class="header-section-number">8.1</span> How big is your <span class="math inline">\(R^2\)</span>?</h2>
<p>One part of regression model diagnostics is to check the fitted model’s <span class="math inline">\(R^2\)</span> value, which gives an indication of the proportion of the variance in the response that has been “explained” by the model. A low value (closer to 0) means that data points are spread far around the best fit line; a high one (close to 1) means that data points are clustered very tightly around the line. A model with a low <span class="math inline">\(R^2\)</span> value is not necessarily “bad” – it may still provide helpful information about a real relationship between your response and predictor. However, that relationship is very “noisy,” which means that your model will have poor predictive power – it will be unable to make predictions with the accuracy and precision you might hope for.</p>
<p>Often, the predictive power of a model, and the <span class="math inline">\(R^2\)</span> value, can be improved by adding additional explanatory variables – that is, fitting a model with more than one explanatory variable. It could have two predictors, three, or as many as you can (sensibly) come up with. This kind of model is called multiple regression. Mathematically, it means fitting a model of the form:</p>
<p><span class="math display">\[
y ~ \beta_0 + \beta_1*x_1 + \beta_2*x_2 + \beta_3*x_3 ...
\]</span></p>
<p>Multiple regression often makes sense when you are studying a complex process where there is most likely “more than one thing going on.” For example, you might consider modelling population growth rates worldwide using a data set including a set of social, economic, health, and political indicators compiled using data from the World Health Organization and partner organizations. The dataset description is available online: <a href="http://www.exploredata.net/Downloads/WHO-Data-Set" class="uri">http://www.exploredata.net/Downloads/WHO-Data-Set</a>. One idea might be to look for a linear relationship between per-capita income and population growth rate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simplify some variable names</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(whodat)[<span class="dv">10</span>] <span class="ot">&lt;-</span> <span class="st">"PopGrowthRate"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(whodat)[<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="st">"IncomePerCapita"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(whodat)[<span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="st">"FemaleSchoolEnrollment"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(PopGrowthRate <span class="sc">~</span> IncomePerCapita, <span class="at">data =</span> whodat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 24 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-who-plot1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-nonlinear_files/figure-html/fig-who-plot1-1.png" class="img-fluid figure-img" width="432"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.1: Population growth rate and per capita income.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>who.m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(PopGrowthRate <span class="sc">~</span> IncomePerCapita, <span class="at">data =</span> whodat)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(who.m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PopGrowthRate ~ IncomePerCapita, data = whodat)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.68051 -0.70998 -0.02006  0.70727  2.78944 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      1.657e+00  1.048e-01   15.81  &lt; 2e-16 ***
IncomePerCapita -2.867e-05  6.218e-06   -4.61 7.72e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.041 on 176 degrees of freedom
  (24 observations deleted due to missingness)
Multiple R-squared:  0.1077,    Adjusted R-squared:  0.1027 
F-statistic: 21.25 on 1 and 176 DF,  p-value: 7.723e-06</code></pre>
</div>
</div>
<p>The <span class="math inline">\(R^2\)</span> value of this model is very low. But that could be because, unsurprisingly, there are <em>many</em> factors contributing to population growth rate, not <em>just</em> income. For example, what about education? Perhaps more-educated women have fewer children, lowering the population growth rate. So we might want to model population growth rate as a function of <em>both</em> income and education.</p>
<p>In R, a multiple regression model can be fitted with a call to <code>lm()</code>. We just add additional predictors to the right hand side of the model formula, separated by <span class="math inline">\(+\)</span> signs. For the WHO example discussed above, for example, we could try:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>who.m2 <span class="ot">&lt;-</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(PopGrowthRate <span class="sc">~</span> IncomePerCapita <span class="sc">+</span> FemaleSchoolEnrollment, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> whodat)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(who.m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PopGrowthRate ~ IncomePerCapita + FemaleSchoolEnrollment, 
    data = whodat)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.43374 -0.52979  0.06017  0.56619  2.48052 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             4.095e+00  3.626e-01  11.293  &lt; 2e-16 ***
IncomePerCapita        -1.102e-05  6.028e-06  -1.827   0.0694 .  
FemaleSchoolEnrollment -3.105e-02  4.504e-03  -6.894 1.06e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9086 on 167 degrees of freedom
  (32 observations deleted due to missingness)
Multiple R-squared:  0.3101,    Adjusted R-squared:  0.3018 
F-statistic: 37.52 on 2 and 167 DF,  p-value: 3.475e-14</code></pre>
</div>
</div>
<p>We would need to follow up with our diagnostics to fully assess these two models, but comparison of the <span class="math inline">\(R^2\)</span> values immediately shows that <span class="math inline">\(R^2\)</span> is much higher for the second model. In other words, the multiple regression has succeeded in explaining more of the variance in population growth rates than the simple linear regression with only one predictor.</p>
</section>
<section id="violations-of-linear-regression-assumptions" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="violations-of-linear-regression-assumptions"><span class="header-section-number">8.2</span> Violations of Linear Regression Assumptions</h2>
<p>In the previous chapter, we learned how to carry out regression diagnostics – to check whether or not the assumptions of linear regression analysis were valid for a particular analysis. If the assumptions are violated, then the conclusions (parameter estimates, but especially standard errors) will be incorrect, and the model results can not be trusted.</p>
<p>For each type of violation, there are some fixes or modifications we can try in order to fit a valid, trustworthy model to our data and still draw reliable conclusions. In this course, we will focus mainly on one type of “fix”: applying transformations to linearize non-linear relationships, and allow us to apply linear regression to the transformed data. This approach is covered in detail in the rest of this chapter.</p>
<p>Before beginning our detailed discussion of transformation, we will briefly discuss several other types of “fixes”. The mathematical foundations of these more complex models are essentially beyond the scope of this class, but you should understand when they might be useful (for example, if you see a certain type of pattern in residual diagnostic plots, which technique might help solve the problem?) and be able to implement them in R.</p>
<p>The table below provides an overview of various problems you might uncover as you do regression diagnostics, along with possible solutions. Each entry in the table is covered in a bit more detail in the subsequent sections of this chapter.</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Assumption</th>
<th>Description of Problem</th>
<th>Options</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Scatterplot (or residual plots) indicate nonlinear relationship</td>
<td>Transform explanatory and or response variables. Alternative: fit a non-linear model using the R function <code>nls()</code></td>
</tr>
<tr class="even">
<td>Independence of errors</td>
<td>ACF plot indicates strong dependence of errors over time (or space)</td>
<td>Fit an “autoregressive” model, where this relationship between subsequent or nearby measurements is expected and accounted for. To do this in R, replace <code>lm(y ~ x)</code> with something like <code>gls(y ~ x, correlation = corAR1(form = ~ 1))</code>.</td>
</tr>
<tr class="odd">
<td>Normality of errors</td>
<td>Residual QQ plots indicates departure from normality</td>
<td>First check if other assumptions may also be violated, and try options listed there. If that fails, you may need to add additional predictor variables to your model; or to fit a generalized linear model, a more sophisticated type of regression that we will not cover in here.</td>
</tr>
<tr class="even">
<td>Equal Variance (homeoskedasticity)</td>
<td>Variance of errors is not constant over the full range of response values, or over time</td>
<td>First, make sure that the linearity assumption is not violated. Next, if you have the option of including additional predictors in your model, it may be helpful. Next, transforming the response variable may help. Finally, if none of those options provide a solution, you can fit a model with non-constant error variance. For example, if variance increases with fitted response values, you can replace <code>lm(y ~ x)</code> with something like <code>nls(y ~ x, weights = varPower())</code></td>
</tr>
</tbody>
</table>
</section>
<section id="non-normal-errors" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="non-normal-errors"><span class="header-section-number">8.3</span> Non-Normal Errors</h2>
<p>Sometimes, during diagnostics for a linear regression model, you will find that residual quantile-quantile plots indicate that linear regression residuals are far from normally distributed. In this case, before trying to modify your model in any way, it is useful to check whether any <em>other</em> assumptions of the linear regression have <em>also</em> been violated. If they have, it is worthwhile to try to deal with those problems first, and see if solving them makes the residuals more normal.</p>
<p>If non-normal residuals are the only apparent problem with a linear regression model, adding additional explanatory variables <em>might</em> help in some cases. Most of the time, you would have to turn to a more sophisticated regression model called a generalized linear model (GLM). Fitting GLMs is beyond the scope of this class, and you will not be asked to do it.</p>
</section>
<section id="non-independence-of-errors" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="non-independence-of-errors"><span class="header-section-number">8.4</span> Non-Independence of Errors</h2>
<p>Sometimes, regression diagnostics (particularly a plot of residuals as a function of time, or an ACF plot) will show that the residuals are not independent. This happens most often when the predictor variable is a temporal or spatial one; data points collected at similar times, or similar locations, are often similar to each other rather than independent.</p>
<p>We will consider a simple example using the price of chicken over time (in constant dollars, adjusted for inflation over time). It seems to make sense to try to predict the price of chicken as a function of time (it’s been getting progressively cheaper for the last century or so): <!--  # chickn <- read.csv("http://www.calvin.edu/~sld33/data/chickn.csv", header = TRUE) --> <!-- % # chickn <- read.csv("https://github.com/selva86/datasets/blob/master/chicken.csv") |> --></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>chickn <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://sldr.netlify.app/data/chickn.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(Price <span class="sc">~</span> Year, <span class="at">data =</span> chickn ) <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>chick.mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Year, <span class="at">data =</span> chickn)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chick.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Year, data = chickn)

Residuals:
   Min     1Q Median     3Q    Max 
-57.07 -20.23  -4.75  13.20  79.98 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 5792.6918   329.9948   17.55   &lt;2e-16 ***
Year          -2.9123     0.1685  -17.29   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 28.48 on 68 degrees of freedom
Multiple R-squared:  0.8146,    Adjusted R-squared:  0.8119 
F-statistic: 298.8 on 1 and 68 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/chickn-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>However, there seems to be a problem with non-independence of the residuals. Price is not independent from year to year; if you know the price was a bit high one year, it’s likely to remain so for the next several years:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">resid</span>(chick.mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/chick-acf-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>This is a big problem, because it tends to result in standard error estimates that are artificially small. In other words: we think we have estimated our slope and intercept parameters <em>much</em> more precisely than we really have, and would report falsely narrow confidence intervals. To fix the problem, we can consider replacing our simple linear regression: <span class="math display">\[
y ~ \beta_0 + \beta_1x + \epsilon
\]</span> (where <span class="math inline">\(\epsilon \sim N(0, \sigma)\)</span>) with a model that expects that subsequent residuals to depend on previous ones, so that the residual for the data point collected at time <span class="math inline">\(t\)</span> is: <span class="math display">\[
e_t = \rho e_{t-1} + \epsilon
\]</span> (where, still, <span class="math inline">\(\epsilon \sim N(0, \sigma)\)</span>; and <span class="math inline">\(\rho\)</span> is a new parameter indicating how strong the dependence over time is.) This is called an AR(1) process, or an auto-regressive process of order 1. It can be fit easily in R using the function <code>gls()</code> instead of . <code>gls()</code> does “generalized least-squares” fitting, and is found in the package <code>nlme</code>. The function call syntax illustrated in this example will work any time the explanatory variable is the time (or space) one that is causing the non-independence.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>chick.mod2 <span class="ot">&lt;-</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gls</span>(Price <span class="sc">~</span> Year, <span class="at">data =</span> chickn, <span class="at">correlation =</span> <span class="fu">corAR1</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chick.mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: Price ~ Year 
  Data: chickn 
       AIC      BIC    logLik
  557.8043 566.6823 -274.9022

Correlation Structure: AR(1)
 Formula: ~1 
 Parameter estimate(s):
      Phi 
0.9483234 

Coefficients:
               Value Std.Error   t-value p-value
(Intercept) 4764.172 1600.4333  2.976802  0.0040
Year          -2.387    0.8171 -2.921499  0.0047

 Correlation: 
     (Intr)
Year -1    

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-1.0593757 -0.5673406 -0.1571088  0.3360972  2.0991647 

Residual standard error: 41.39414 
Degrees of freedom: 70 total; 68 residual</code></pre>
</div>
</div>
<p>If you plot the residuals of this new model, and plot the ACF, you will see that the correlation coefficients <em>still have high values</em>. However, in the new <code>gls()</code> fit, this correlation has now been taken into account in the standard errors (which are larger – compare the coefficient tables to verify it), so it is OK now to trust the model parameter estimates and predictions.</p>
</section>
<section id="heteroskedasticity-non-constant-error-variance" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="heteroskedasticity-non-constant-error-variance"><span class="header-section-number">8.5</span> Heteroskedasticity (Non-constant Error Variance)</h2>
<p>Sometimes, model diagnostics for a linear regression indicate that variance of errors is not constant over the full range of response values. Often, it is the case that the error variance grows larger as the predicted response value grows larger, resulting in a “trumpet-like” shape in the plot of residuals versus fitted values.</p>
<p>If you spot this problem, first, make sure that the linearity assumption is not violated. Next, if you have the option of including additional predictors in your model, it may be helpful. Next, transforming the response variable may help. Specifically, a log or square-root transformation of the response variable may be useful. (See more details and examples later in this chapter, when transformations are discussed in detail.)</p>
<p>Finally, if none of the previous options provide a solution, you can fit a model that actually <em>expects</em> and accounts for non-constant error variance. We will not cover this topic in any detail, but this brief example is included for your future reference (outside this class). Example: if variance increases with fitted response values, you can fit an appropriate model with the <code>gls</code> function from the <code>nlme</code> package. To do so, replace <code>lm(y ~ x)</code> with something like <code>nls(y ~ x, weights = varPower())</code>.</p>
<p>Here is a brief example, using the <code>Ornstein</code> dataset from the <code>car</code> package. It gives data on 248 Canadian companies, collected in the mid-1970s. The variable <code>assets</code> gives each company’s assets in millions of dollars, and <code>interconnects</code> gives the number of director and executive positions that are shared with other firms. A scatter plot shows that the richest companies have many of these “interlocks”, so we might model assets as a function of interlocks…however, the residuals have non-constant variance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(assets <span class="sc">~</span> interlocks, <span class="at">data =</span> Ornstein)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/Ornstein-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>om <span class="ot">&lt;-</span> <span class="fu">lm</span>(assets <span class="sc">~</span> interlocks, <span class="at">data =</span> Ornstein)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(om) <span class="sc">~</span> <span class="fu">fitted</span>(om))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/Ornstein-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>We can try to correct for this problem by fitting a model that “expects” this non-constant variance, by using the function <code>gls</code> with the input <code>weights = varPower()</code>. (There are many other ways to model non-constant error variance; this small example gives you just a taste, and for this course, you would not be expected to deal with any cases other than ones like this, where error variance increases with fitted values.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>om2 <span class="ot">&lt;-</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gls</span>(assets <span class="sc">~</span> interlocks, <span class="at">data =</span> Ornstein, <span class="at">weights =</span> <span class="fu">varPower</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As with the non-independence case, if you plot the residuals for this model, you will see that they DO still have non-constant variance…but again, now it is OK because our model has taken it into account, and computed parameter estimates and standard errors appropriately.</p>
</section>
<section id="non-linear-relationships" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="non-linear-relationships"><span class="header-section-number">8.6</span> Non-linear Relationships</h2>
<p>The rest of this chapter will provide detailed information on how to deal with some non-linear relationships in regression.</p>
<p>Linear regression assumes a linear relationship between predictor and response variables, but not all relationships between pairs of quantitative variables are linear. There are two common ways to deal with nonlinear relationships:</p>
<div class="enumerate">
<ol>
<li>Transform the data before beginning linear regression analysis, so that there <em>is</em> a linear relationship between the (transformed) variables.</li>
<li>Fit a model that explicitly expects, and accounts for, the nonlinear relationship between the two variables.</li>
</ol>
</div>
<!-- end enumerate -->
</section>
<section id="transformations-in-linear-regression" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="transformations-in-linear-regression"><span class="header-section-number">8.7</span> Transformations in Linear Regression</h2>
<section id="reasons-for-using-transformations" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="reasons-for-using-transformations"><span class="header-section-number">8.7.1</span> Reasons for Using Transformations</h3>
<p>The applicability of linear models can be extended through the use of various transformations of the data. There are several reasons why one might consider a transformation of the predictor or response (or both).</p>
<ol type="1">
<li><p>To correspond to a theoretical model.</p>
<p>Sometimes we have <em>a priori</em> information that tells us what kind of non-linear relationship we should anticipate. For example, an experiment to estimate Planck’s constant (<span class="math inline">\(\hbar\)</span>) using LED lights and a voltage meter is based on the relationship</p>
<p><span class="math display">\[
    V_a = \frac{\hbar c }{e \lambda} + k
\]</span></p>
<p>where <span class="math inline">\(V_a\)</span> is the activation voltage (the voltage at which the LED just begins to emit light), <span class="math inline">\(c\)</span> is the speed of light, <span class="math inline">\(e\)</span> is the energy of an electron, <span class="math inline">\(\lambda\)</span> is the frequency of the light emitted, and <span class="math inline">\(k\)</span> is a constant that relates to the energy losses inside the semiconductor’s p-n junction. If we take <span class="math inline">\(c\)</span> and <span class="math inline">\(e\)</span> as known for now (in a fancier version we would work their uncertainties into this, too), we can design an experiment that measures <span class="math inline">\(V_a\)</span> and <span class="math inline">\(\lambda\)</span> for a number of different colors.</p>
<p>A little algebra gives us</p>
<p><span class="math display">\[
    V_a = \frac{\hbar c }{e} \cdot \frac{1}{\lambda} + k
\]</span></p>
<p>So if we fit a model with <span class="math inline">\(V_a\)</span> as the response and <span class="math inline">\(\frac{1}{\lambda}\)</span> as the predictor, then the slope and intercept of the resulting least squares regression line will give us an estimate for <span class="math inline">\(\frac{\hbar c }{e}\)</span>, from which we can solve for <span class="math inline">\(\hbar\)</span>. (Note: if we know uncertainties for <span class="math inline">\(c\)</span>, for <span class="math inline">\(e\)</span>, and for the slope, we can compute an estimated uncertainty for <span class="math inline">\(\hbar\)</span> using our propagation of uncertainty methods.)</p>
<p>Theory says that a scatter plot of <span class="math inline">\(V_a\)</span> and <span class="math inline">\(1/\lambda\)</span> should form a straight line, so the model we would fit would look something like</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(voltage <span class="sc">~</span> <span class="fu">I</span>(<span class="dv">1</span><span class="sc">/</span>wavelength), <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We need to wrap <code>1/lambda</code> in <code>I()</code> because the arithmetic symbols (<code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, and <code>^</code>) have special meanings inside the formula for a model. <code>I()</code> stands for <em>inhibit</em> special interpretation.</p>
<p>Notice that the intercept is not directly involved in estimating <span class="math inline">\(\hbar\)</span>, but that we can’t fit the line and obtain our slope without it.</p>
<p>Many non-linear relationships can be transformed to linearity. <a href="#exr-transformations">Exercise&nbsp;<span>8.2</span></a> presents several more examples and asks you to determine a suitable transformation.</p></li>
<li><p>To obtain a better fit.</p>
<p>If a scatterplot or residual plot shows a clearly non-linear pattern to the data, then it would be inappropriate to fit a linear regression (and conclusions drawn from that model would be incorrect and misleading). In the absence of theoretical reasons to expect a particular mathematical relationship between the variables being studied, we may select transformations based on the shape of the relationship as revealed in a scatterplot. <a href="#sec-ladder-of-re-expression"><span>Section&nbsp;8.7.4</span></a> provides some guidance for selecting transformations in this situation.</p></li>
<li><p>To obtain better residual behavior.</p>
<p>Sometimes transformations are used to improve the agreement between the data and the assumptions about the error terms in the model. For example, if the variance in the response appears to increases as the predictor increases, a logarithmic or square root transformation of the response may decrease the disparity in variance. <!-- Some transformations are used to improve the agreement between the --> <!-- data and the assumptions about the error terms in the model.  --> <!-- For example, if data are heteroskedastic -- for example,  --> <!-- if the variance in the response appears to increase as the predictor increases --  --> <!-- a logarithmic or square root transformation of the response may help.  --></p></li>
</ol>
<p>In practice, all three of these issues are intertwined. A transformation that improves the fit, for example, may or may not have a good theoretical interpretation. Similarly, a transformation performed to achieve <strong>homoskedasticity</strong> <!--  --> <!--  --> (equal variance; the opposite is called <strong>heteroskedasticity</strong>) may result in a fit that does not match the overall shape of the data very well. Despite these potential problems, there are many situations where a relatively simple transformation is all that is needed to greatly improve the model. Here, when we say “improve” the model, we mean that the assumptions of the model are satisfied, and the model fits the data acceptably well.</p>
</section>
<section id="three-important-laws" class="level3" data-number="8.7.2">
<h3 data-number="8.7.2" class="anchored" data-anchor-id="three-important-laws"><span class="header-section-number">8.7.2</span> Three Important Laws</h3>
<p>In the sciences, relationships between variables based on some scientific theory are often referred to as “laws”. Many of these fall into one of three categories that are easily handled by transforming the data and fitting a linear regression model.</p>
<section id="linear-laws" class="level4" data-number="8.7.2.1">
<h4 data-number="8.7.2.1" class="anchored" data-anchor-id="linear-laws"><span class="header-section-number">8.7.2.1</span> Linear Laws</h4>
<p>We’ve already talked about linear relationships, but it is worth mentioning them again because there are so many situations in which a linear relationship arises.</p>
</section>
<section id="power-laws" class="level4" data-number="8.7.2.2">
<h4 data-number="8.7.2.2" class="anchored" data-anchor-id="power-laws"><span class="header-section-number">8.7.2.2</span> Power Laws</h4>
<p>Relationships of the form <span class="math display">\[
y = A x^p
\]</span> are often called power laws. The two parameters are the exponent <span class="math inline">\(p\)</span> and a constant of proportionality <span class="math inline">\(A\)</span>. Power laws can be linearized by taking logarithms: <span class="math display">\[
\log(y) = \log(A x^p) = \log(A) + p \log(x)
\]</span> So if we fit a model of the form</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">log</span>(y) <span class="sc">~</span> <span class="fu">log</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then <span class="math inline">\(\beta_0 = \log(A)\)</span> and <span class="math inline">\(\beta_1 = p\)</span>. If a power law is a good fit for the data then</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( <span class="fu">log</span>(y) <span class="sc">~</span> <span class="fu">log</span>(x) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>will produce a roughly linear plot.</p>
<p>Fitting a power law results in estimates for the parameters <span class="math inline">\(\beta_0 = \log(A)\)</span> and <span class="math inline">\(\beta_1 = p\)</span>. Note that we can use logarithms with any base for this transformation. Typically natural logarithms are used (that’s what <code>log()</code> does in R). In some specific applications we might use base 10 logarithms (<code>log10()</code> in R) or base 2 logarithms (<code>log2()</code> in R); this yields the commonly used scale for <span class="math inline">\(\beta_0 = \log(A)\)</span>, the constant of proportionality.</p>
<p>Some common situations that are modeled with power laws include drag force vs speed, velocity vs.&nbsp;force, and frequency vs.&nbsp;force.</p>
</section>
<section id="exponential-laws" class="level4" data-number="8.7.2.3">
<h4 data-number="8.7.2.3" class="anchored" data-anchor-id="exponential-laws"><span class="header-section-number">8.7.2.3</span> Exponential Laws</h4>
<p>Relationships of the form <span class="math display">\[
y = A B^x = A e^{Cx}
\]</span> are often called exponential laws. The two parameters are the base <span class="math inline">\(B = e^C\)</span> and a constant of proportionality <span class="math inline">\(A\)</span>. Exponential laws can also be linearized by taking logarithms: <span class="math display">\[
\log(y) = \log(A B^x) = \log(A) + x \log(B)
\]</span> So if we fit a model of the form</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">log</span>(y) <span class="sc">~</span> x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then <span class="math inline">\(\beta_0 = \log(A)\)</span> and <span class="math inline">\(\beta_1 = \log(B) = C\)</span>. If an exponential law is a good fit for the data then</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( <span class="fu">log</span>(y) <span class="sc">~</span> x )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>will produce a roughly linear plot.</p>
<p>Fitting an exponential law results in estimates for the parameters <span class="math inline">\(\beta_0 = \log(A)\)</span> and <span class="math inline">\(\beta_1 = \log(B) = C\)</span>. Again, we will generally use natural logarithms. In this course, if you see a <code>log()</code> without an indication of the base of the logarithm, you can assume it is base “e”, a natural logarithm. Similarly, remember that for R, the function <code>log()</code> takes the natural logarithm.</p>
<p>Some common situations that are modeled with exponential laws include population growth and radioactive decay. Note that exponential growth models are typically only good approximations over a limited range since exponential functions eventually grow quickly, and often some external constraints will limit this growth. For example, a culture of bacteria may grow roughly exponentially for a while, but eventually, limits on space and nourishment will make it impossible for exponential growth to continue.</p>
</section>
<section id="log-log-and-semi-log-plots" class="level4" data-number="8.7.2.4">
<h4 data-number="8.7.2.4" class="anchored" data-anchor-id="log-log-and-semi-log-plots"><span class="header-section-number">8.7.2.4</span> Log-log and semi-log plots</h4>
<p>Graphs of <span class="math inline">\(\log(y)\)</span> vs.&nbsp;<span class="math inline">\(\log(x)\)</span> (log-log) or <span class="math inline">\(\log(y)\)</span> vs <span class="math inline">\(x\)</span> (semi-log) can be used to assess whether the power law or exponential law appears to apply in a given situation. If the law were a perfect description of the situation, all the points on the log-log or semi-log plot would fall along a straight line. In practice, the fit won’t be perfect, but the plot is a useful diagnostic. For example, you can compare a plot of <span class="math inline">\(y\)</span> as a function of <span class="math inline">\(x\)</span> with a log-log or semi-log plot, and see which one shows the most linear relationship between the two variables.</p>
<p>In the old days, before computers could readily transform the data, special graph paper was produced with semi-log or log-log scales to facilitate this sort of plot. <!--  R can also create plots with transformed scales.   --> <!-- % Here are some --> <!--  examples using artificial data satisfying a power law (with exponent 1.5). --> R can easily create plots with transformed scales. Use <code>gf_refine()</code> with input <code>scales_*_log10()</code> to your call to <code>gf_point()</code>, as detailed in the example below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> x<span class="sc">^</span><span class="fl">1.5</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(y) <span class="sc">~</span> <span class="fu">log</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(y) <span class="sc">~</span> x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(y <span class="sc">~</span> x) <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_x_log10</span>(), <span class="fu">scale_y_log10</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(y <span class="sc">~</span> x) <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_log10</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>As expected, the log-log transformation makes things linear. Of course, with real data, the fit won’t be perfect like this.</p>
</section>
</section>
<section id="other-models-that-can-be-transformed-to-linear" class="level3" data-number="8.7.3">
<h3 data-number="8.7.3" class="anchored" data-anchor-id="other-models-that-can-be-transformed-to-linear"><span class="header-section-number">8.7.3</span> Other Models That Can Be Transformed to Linear</h3>
<p>The three laws above are not the only kinds of relationships that can be transformed to linear.</p>
<div id="exm-chem-eng-book" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.1 </strong></span>A chemical engineering text book suggest a law of the form <span class="math display">\[
\log( - \frac{dC}{dt} ) =  \log(k) + \alpha \log(C)
\]</span> where <span class="math inline">\(C\)</span> is concentration and <span class="math inline">\(t\)</span> is time.</p>
<p>This is equivalent to <span class="math display">\[
\begin{aligned}
- \frac{dC}{dt}  &amp;=  k \cdot C^\alpha
\\
- \int C^{-\alpha} \; dC  &amp;=  \int k \;dt
\\
- \frac{1}{1-\alpha} C^{1-\alpha} &amp;=  k t + d
\\
\frac{1}{\beta} C^{-\beta} &amp; = k t + d
\\
C^{-\beta} &amp; = \beta k t + \beta d
\end{aligned}
\]</span></p>
<p>If we know <span class="math inline">\(\beta = \alpha - 1\)</span> (i.e., if we know <span class="math inline">\(\alpha\)</span>), then we can fit a linear model using</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(C<span class="sc">^</span>(<span class="sc">-</span>beta) <span class="sc">~</span> t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The intercept of such a model will be <span class="math inline">\(\beta d\)</span> and the slope will be <span class="math inline">\(\beta k\)</span>, from which we can easily recover <span class="math inline">\(d\)</span> and <span class="math inline">\(k\)</span>.</p>
<p>Alternatively, if we know <span class="math inline">\(d = 0\)</span> (i.e., if we know that <span class="math inline">\(C = 0\)</span> when <span class="math inline">\(t = 0\)</span>), then we can use <span class="math display">\[
\begin{aligned}
    \log( C^{-\beta} )  = -\beta \log(C) &amp;= \log(\beta k t ) = \log(\beta k) + \log t
\\
\log(C) &amp;= - \frac{\log(\beta k)}{\beta} - \frac{1}{\beta} \log t
\end{aligned}
\]</span></p>
<p>Now if we fit a model of the form</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">log</span>(C) <span class="sc">~</span> <span class="fu">log</span>(t))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>the intercept will be <span class="math inline">\(\frac{-\log(\beta k)}{\beta}\)</span> and the slope will be <span class="math inline">\(\frac{-1}{\beta}\)</span>. From this we can solve for <span class="math inline">\(k\)</span> and <span class="math inline">\(\beta\)</span>.</p>
</div>
<!-- end example -->
<div id="exm-chem-eng-book-2" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.2 </strong></span>Continuing the previous example, we will fit the following data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Concentration <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">150</span>, <span class="dv">200</span>, <span class="dv">250</span>, <span class="dv">300</span>),               <span class="co"># minutes</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">concentration =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">38</span>, <span class="fl">30.6</span>, <span class="fl">25.6</span>, <span class="fl">22.2</span>, <span class="fl">19.5</span>, <span class="fl">17.4</span>) <span class="co"># mol/dm^3 * 10^3</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(concentration <span class="sc">~</span> time, <span class="at">data =</span> Concentration)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>under the assumption that <span class="math inline">\(\alpha = 2\)</span>, so <span class="math inline">\(\beta = 1\)</span>. In this case, our relationship becomes <span class="math display">\[
\frac{1}{C}  = k t + d \;.
\]</span> We can now fit a model and see how well it does.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>conc.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="dv">1</span><span class="sc">/</span>concentration <span class="sc">~</span> time, <span class="at">data =</span> Concentration)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(conc.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = 1/concentration ~ time, data = Concentration)

Residuals:
         1          2          3          4          5          6          7 
-1.175e-04 -4.144e-05  8.281e-05  2.259e-04 -3.128e-05 -3.398e-05 -8.447e-05 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 2.012e-02  8.762e-05   229.6 2.97e-11 ***
time        1.248e-04  4.860e-07   256.8 1.70e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001286 on 5 degrees of freedom
Multiple R-squared:  0.9999,    Adjusted R-squared:  0.9999 
F-statistic: 6.593e+04 on 1 and 5 DF,  p-value: 1.7e-11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(conc.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %       97.5 %
(Intercept) 0.0198922974 0.0203427516
time        0.0001235447 0.0001260434</code></pre>
</div>
</div>
<p>This provides estimates for the intercept <span class="math inline">\(\beta d = d\)</span> and the slope <span class="math inline">\(\beta k = k\)</span><br>
of our model (because we are assuming that <span class="math inline">\(\beta = 1\)</span>; in the general case, we could divide by <span class="math inline">\(\beta\)</span> to obtain estimates for <span class="math inline">\(d\)</span> and <span class="math inline">\(k\)</span>.)</p>
<p>Of course, we should always look to see whether the fit is a good fit. <!--  mplot(conc.model, w = 1:2)  # residual plot and qq-plot of residuals --></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(conc.model) <span class="sc">~</span> <span class="fu">fitted</span>(conc.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(conc.model)) <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_qqline</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Notice that these residuals are very small relative to the values for concentration. (We can see this from the vertical scale of the plot and also from the small value for residual standard error in the summary output.) The shape of the residual plot would be more disturbing if the magnitudes were larger and if there were more data. As is, even if there is some systematic problem, it is roughly five orders of magnitude smaller than our concentration measurements, which likely can’t be measured to that degree of accuracy.</p>
<p>If we want to show the fit on top of the original data, we must remember to untransform the response, since the model we fitted is a model for <span class="math inline">\(1/C\)</span>, but we want to show a model for <span class="math inline">\(C\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( concentration <span class="sc">~</span> time, <span class="at">data =</span> Concentration ) <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_line</span>( <span class="dv">1</span><span class="sc">/</span><span class="fu">fitted</span>(conc.model) <span class="sc">~</span> time, <span class="at">data =</span> Concentration)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="432"></p>
</div>
</div>
</div>
<!-- end example -->
</section>
<section id="sec-ladder-of-re-expression" class="level3" data-number="8.7.4">
<h3 data-number="8.7.4" class="anchored" data-anchor-id="sec-ladder-of-re-expression"><span class="header-section-number">8.7.4</span> The Ladder of Re-expression</h3>
<p>Sometimes we have data for which there is no theory (yet) to suggest the form of a model. In such a case, we may let the data help suggest a model. If we find a model that fits well, we can return to the question of whether there is an explanation for that type of model.</p>
<p>In the 1970s, Mosteller and Tukey (<span class="citation" data-cites="Tukey:1977:EDA">Tukey (<a href="references.html#ref-Tukey:1977:EDA" role="doc-biblioref">1977</a>)</span>, <span class="citation" data-cites="Mosteller:1977:DataAnalysis">Mosteller and Tukey (<a href="references.html#ref-Mosteller:1977:DataAnalysis" role="doc-biblioref">1977</a>)</span>) introduced what they called the <strong>ladder of re-expression</strong> and <strong>bulge rules</strong> that can be used to suggest an appropriate transformation to improve the fit when the relationship between two variables (<span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> in our examples) is monotonic and has a single bend. Their idea was to apply a power transformation to <span class="math inline">\(x\)</span> or <span class="math inline">\(y\)</span> or both – that is, to work with <span class="math inline">\(x^a\)</span> and <span class="math inline">\(y^b\)</span> for an appropriate choice of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. Tukey called this ordered list of transformations the <em>ladder of re-expression</em>. The identity transformation has power <span class="math inline">\(1\)</span>. The logarithmic transformation is a special case and is included in the list associated with a power of <span class="math inline">\(0\)</span>. The direction of the required transformation can be obtained from <a href="#fig-tukey-bulge">Figure&nbsp;<span>8.2</span></a> and <a href="#tbl-ladder">Table&nbsp;<span>8.1</span></a>, which shows four bulge types, represented by the curves in each of the four quadrants. A bulge can potentially be straightened by applying a transformation to one or both variables, moving up or down the ladder as indicated by the arrows. More severe bulges require moving farther up or down the ladder. <!-- \authNote{ed: There is a standard ordering of quadrants in mathematics, so labeling --> <!-- isn't needed.  We could use directions (upper right), but I don't want to add  --> <!-- quadrant numbers to the figure.  Also in next example.  --- 2010-11-8}<!--  --> –&gt; A curve bulging in the same direction as the one in the first quadrant of <a href="#fig-tukey-bulge">Figure&nbsp;<span>8.2</span></a>, for example, might be straightened by moving up the ladder of transformations for <span class="math inline">\(x\)</span> or <span class="math inline">\(y\)</span> (or both), while a curve like the one in the second quadrant, might be straightened by moving up the ladder for <span class="math inline">\(y\)</span> or down the ladder for <span class="math inline">\(x\)</span>.</p>
<div class="columns">
<div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div id="fig-tukey-bulge" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-nonlinear_files/figure-html/fig-tukey-bulge-1.png" class="img-fluid figure-img" width="432"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.2: Tukey and Mosteller’s bulging rule</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div id="tbl-ladder" class="anchored">
<table class="table">
<caption>Table&nbsp;8.1: Ladder of re-expression</caption>
<thead>
<tr class="header">
<th>power</th>
<th>transformation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(x \mapsto x^3\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\(x \mapsto x^2\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\(x \mapsto x\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac12\)</span></td>
<td><span class="math inline">\(x \mapsto \sqrt{x}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(x \mapsto \log(x)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(-1\)</span></td>
<td><span class="math inline">\(x \mapsto \frac1x\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(-2\)</span></td>
<td><span class="math inline">\(x \mapsto \frac{1}{x^2}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>This method focuses primarily on transformations designed to improve the overall fit. The resulting models may or may not have a natural, or obvious, interpretation. These transformations also affect the shape of the distributions of the explanatory and response variables and, more importantly, of the residuals from the linear model (see <a href="#exr-tukey-bulge-skew">Exercise&nbsp;<span>8.3</span></a>). When several different transformations lead to reasonable linear fits, these other factors may lead us to prefer one over another.</p>
<div id="exm-tukey-bulge" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.3 </strong></span><strong>Q.</strong> The scatterplot in <a href="#fig-tukey-bulge-example">Figure&nbsp;<span>8.3</span></a> shows a curved relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. What transformations of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> improve the linear fit?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tukey-bulge-example" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-nonlinear_files/figure-html/fig-tukey-bulge-example-1.png" class="img-fluid figure-img" width="432"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.3: A scatterplot illustrating a non-linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><strong>A.</strong> This type of bulge appears in quadrant IV of <a href="#fig-tukey-bulge">Figure&nbsp;<span>8.2</span></a>, so we can hope to improve the fit by moving up the ladder for <span class="math inline">\(x\)</span> or down the ladder for <span class="math inline">\(y\)</span>. As we see in <a href="#fig-tukey-bulge-many">Figure&nbsp;<span>8.4</span></a>, the fit generally improves as we move down and to the right – but not too far, lest we over-correct. A <span class="math inline">\(\log\)</span>-transformation of the response (<span class="math inline">\(a = 1\)</span>, <span class="math inline">\(b = 0\)</span>) seems to be especially good in this case. Not only is the resulting relationship quite linear, but the residuals appear to have a better distribution as well.</p>
</div>
<!-- end example -->
<div class="cell">
<div class="cell-output-display">
<div id="fig-tukey-bulge-many" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-nonlinear_files/figure-html/fig-tukey-bulge-many-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.4: Using the ladder of re-expression to find a better fit.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div id="exm-balldrop" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.4 </strong></span>Some physics students conducted an experiment in which they dropped steel balls from various heights and recorded the time until the ball hit the floor. We begin by fitting a linear model to this data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ball.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> height, <span class="at">data =</span> BallDrop)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ball.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = time ~ height, data = BallDrop)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0200108 -0.0089383  0.0001623  0.0082016  0.0186519 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.190243   0.004303   44.21   &lt;2e-16 ***
height      0.251841   0.005516   45.66   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01009 on 28 degrees of freedom
Multiple R-squared:  0.9867,    Adjusted R-squared:  0.9863 
F-statistic:  2085 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(time <span class="sc">~</span> height, <span class="at">data =</span> BallDrop) <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/balldrop-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(ball.model) <span class="sc">~</span> <span class="fu">fitted</span>(ball.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/balldrop-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>At first glance, the large value of <span class="math inline">\(r^2\)</span> and the reasonably good fit in the scatterplot might leave us satisfied that we have found a good model. But a look at the residual plot reveals a clear curvilinear pattern in this data. A knowledgeable physics student knows that (ignoring air resistance) the time should be proportional to the <em>square root</em> of the height. This transformation agrees with Tukey’s ladder of re-expression, which suggests moving down the ladder for <code>height</code> or up the ladder for <code>time</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ball.modelT <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> <span class="fu">sqrt</span>(height), <span class="at">data =</span> BallDrop)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ball.modelT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = time ~ sqrt(height), data = BallDrop)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0087773 -0.0038851  0.0000571  0.0030558  0.0125552 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.016078   0.004084   3.937 0.000498 ***
sqrt(height) 0.430803   0.004863  88.580  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.005225 on 28 degrees of freedom
Multiple R-squared:  0.9964,    Adjusted R-squared:  0.9963 
F-statistic:  7846 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(time <span class="sc">~</span> <span class="fu">sqrt</span>(height), <span class="at">data =</span> BallDrop) <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>(time <span class="sc">~</span> <span class="fu">sqrt</span>(height), <span class="at">data =</span> BallDrop) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/balldrop-transT-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(ball.modelT) <span class="sc">~</span> <span class="fu">fitted</span>(ball.modelT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/balldrop-transT-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>This model does indeed fit better, but the residual plot indicates that there may be some inaccuracy in the measurement of the height. In this experiment, the apparatus was set up once for each height and then several observations were made. So any error in this set-up affected all time measurements for that height in the same way. This could explain why the residuals for each height are clustered the way they are since it violates the assumption that the errors are <em>independent</em>. (See <a href="#exm-balldrop-rm">Example&nbsp;<span>8.5</span></a> for a simple attempt to deal with this problem.)</p>
</div>
<!-- end example -->
<!-- It is also important to note that although $r^2$ is very large in this model, -->
<!-- %it no longer has the usual interpretation because the model does not -->
<!-- have an intercept term.  Exercise~@prob:r2NoIntercept explores  -->
<!-- %this further. -->
<div id="exm-balldrop-rm" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.5 </strong></span>One simple way to deal with the lack of independence in the previous example is to average all the readings made at each height. (This works reasonably well in our example because we have nearly equal numbers of observations at each height.) We pay for this data reduction in a loss of degrees of freedom, but it may be easier to justify that the errors in average times at each height are independent (if we believe that the errors in the height set-up are independent and not systematic).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>BallDropAvg <span class="ot">&lt;-</span> BallDrop <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(height) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">time =</span> <span class="fu">mean</span>(time))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>ball.modelA <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> <span class="fu">sqrt</span>(height), <span class="at">data =</span> BallDropAvg)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ball.modelA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = time ~ sqrt(height), data = BallDropAvg)

Residuals:
         1          2          3          4          5          6 
 0.0039552 -0.0040318  0.0028227 -0.0051717  0.0001571  0.0022686 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.016078   0.007404   2.172   0.0956 .  
sqrt(height) 0.430803   0.008816  48.863 1.05e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.004236 on 4 degrees of freedom
Multiple R-squared:  0.9983,    Adjusted R-squared:  0.9979 
F-statistic:  2388 on 1 and 4 DF,  p-value: 1.05e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(time<span class="sc">~</span> height, <span class="at">data =</span> BallDropAvg) <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/balldrop-avg-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(ball.modelA) <span class="sc">~</span> <span class="fu">fitted</span>(ball.modelA))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/balldrop-avg-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Using a square root transformation on averaged <code>height</code> measurements in the <code>BallDrop</code> data gives a similar fit but a very different residual plot. The interpretation of this model is also different.</p>
<p>Notice that the parameter estimates are essentially the same as in the preceding example. The estimate for <span class="math inline">\(\sigma\)</span> has decreased some. This makes sense since we are now estimating the variability in <em>averaged</em> measurements rather than in individual measurements.</p>
<p>Of course, we’ve lost a lot of degrees of freedom, and as a result, the standard error for our parameter estimate is about twice as large as before. This might have been different; had the mean values fit especially well, our standard error might have been smaller despite the reduced degrees of freedom.</p>
<p>One disadvantage of the data reduction is that it is hard to interpret the residuals (because there are fewer of them). At first glance there appears to be a downward trend in the residuals, but this is largely driven by the fact that the largest residual happened to be for the smallest fit.</p>
</div>
<!-- end example -->
<div id="exm-soap" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.6 </strong></span><strong>Q.</strong> Rex Boggs of Glenmore State High School in Rockhampton, Queensland, had an interesting hypothesis about the rate at which bar soap is used in the shower. He writes:</p>
<blockquote class="blockquote">
<p>I had a hypothesis that the daily weight of my bar of soap [in grams] in my shower wasn’t a linear function, the reason being that the tiny little bar of soap at the end of its life seemed to hang around for just about ever. I wanted to throw it out, but I felt I shouldn’t do so until it became unusable. And that seemed to take weeks.</p>
</blockquote>
<blockquote class="blockquote">
<p>Also I had recently bought some digital kitchen scales and felt I needed to use them to justify the cost. I hypothesized that the daily weight of a bar of soap might be dependent upon surface area, and hence would be a quadratic function .</p>
</blockquote>
<blockquote class="blockquote">
<p>The data ends at day 22. On day 23 the soap broke into two pieces and one piece went down the plughole.</p>
</blockquote>
<p>The data indicate that although Rex showered daily, he failed to record the weight for some of the days.</p>
<p>What do the data say in regard to Rex’s hypothesis?</p>
<p><strong>A.</strong> Rex’s assumption that weight should be a (quadratic) function of time does not actually fit his intuition. His intuition corresponds roughly to the differential equation <span class="math display">\[
\Partial{t}{W} = k W^{2/3}\,,
\]</span> for some negative constant <span class="math inline">\(k\)</span> since the rate of change should be proportional to the surface area remaining. (We are assuming that the bar shrinks in such a way that its shape remains proportionally unaltered.) Solving this equation (by separation of variables) gives <!-- $$  --> <!-- \log(W) = k t + C \;. --> <!-- $$  --> <span class="math display">\[
W^{1/3} = k t + C
\;.
\]</span> We can fit untransformed and transformed models (<code>weight^(1/3) ~ day</code>) to this data and compare.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>soap.model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> day, <span class="at">data =</span> Soap)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(soap.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight ~ day, data = Soap)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.2436 -1.2950  0.3078  1.3942  5.5040 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 123.1408     1.3822   89.09   &lt;2e-16 ***
day          -5.5748     0.1068  -52.19   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.949 on 13 degrees of freedom
Multiple R-squared:  0.9953,    Adjusted R-squared:  0.9949 
F-statistic:  2724 on 1 and 13 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The scatterplot in <a href="#fig-soap">Figure&nbsp;<span>8.5</span></a> (darker line) indicate that the untransformed model is already a good fit.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>soap.model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">I</span>(weight<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)) <span class="sc">~</span> day, <span class="at">data =</span> Soap)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(soap.model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = I(weight^(1/3)) ~ day, data = Soap)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.31107 -0.13666  0.01605  0.15044  0.20095 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.297706   0.083813   63.21  &lt; 2e-16 ***
day         -0.146980   0.006477  -22.69 7.67e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1788 on 13 degrees of freedom
Multiple R-squared:  0.9754,    Adjusted R-squared:  0.9735 
F-statistic:   515 on 1 and 13 DF,  p-value: 7.669e-12</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-soap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-nonlinear_files/figure-html/fig-soap-1.png" class="img-fluid figure-img" width="432"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.5: Comparing untransformed (darker) and transformed (lighter) fits to soap use data.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<!--  -->
<p>The transformed model in this case actually fits worse. The higher value of <span class="math inline">\(r^2\)</span> for the untransformed model is an indication that the untransformed model explains a larger proportion of the variance in soap weights. It is left as an exercise for you to examine diagnostic plots of the model residuals in both cases; you should see that neither one looks markedly better than the other. (There is perhaps an issue with a small amount of non-independence, or correlation over time, of the residuals; we might expect that with data collected over time. However, the dataset is so small that it is hard to tell for sure if the problem is real and worth worrying about.) <a href="#fig-soap">Figure&nbsp;<span>8.5</span></a> shows a scatterplot with both fits. The data do not support Rex’s assumption that a transformation is necessary. <!--  We can also fit a quadratic model of the form \verb!Weight ~ I(Day^2)!, --> <!-- % but this model is worse still.  Fitting a full quadratic model requires  --> <!--  two predictors (\verb!Day! and \verb!Day^2!) and so will have to wait --> <!-- % until our discussion of multiple linear regression.   --> The scatterplot and especially the residual plots both show that the residuals are mostly positive near the ends of the data and negative near the center. Part of this is driven by a flattening of the pattern of data points near the end of the measurement period. Perhaps as the soap became very small, Rex used slightly less soap than when the soap was larger. <a href="#exr-soap">Exercise&nbsp;<span>8.1</span></a> asks you to remove the last few observations and see how that affects the models.</p>
<p>Finally, since a linear model appears to fit at least reasonably well (but see <a href="#exr-soap">Exercise&nbsp;<span>8.1</span></a>), we can give a confidence interval for <span class="math inline">\(\beta_1\)</span>, the mean amount of soap Rex uses each shower. <!-- \authNoted{check regression diagnostics for soap models -- some cause for worry}<!--  --> –&gt; <!-- \authNote{in text reference for quote from Rex? --2010-11-27}<!--  --> –&gt;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(soap.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) 120.154672 126.126895
day          -5.805514  -5.344014</code></pre>
</div>
</div>
</div>
<!-- end example -->
</section>
</section>
<section id="nonlinear-least-squares" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="nonlinear-least-squares"><span class="header-section-number">8.8</span> Nonlinear Least Squares</h2>
<p>Another approach to non-linear relationships is called <strong>nonlinear least squares</strong> or <strong>nonlinear regression</strong>. In this approach, instead of attempting to transform the relationship until it becomes linear, we fit a nonlinear function by minimizing the the sum of the squared residuals relative to that (parameterized) nonlinear function (form). That is, our model now becomes <span class="math display">\[
y = f(x) + \varepsilon
\]</span> where <span class="math inline">\(f\)</span> may be any parameterized function.</p>
<p>The R function for fitting these models is <code>nls()</code>. This function works much like <code>lm()</code>, but there are some important differences:</p>
<div class="enumerate">
<ol type="a">
<li>Because the model does not have to be linear, we have to use a more verbose description of the model.</li>
<li>Numerical optimization is used to fit the model, and the algorithm used needs to be given a reasonable starting point for its search. Specifying this starting point simultaneously lets R know what the parameters of the model are. (Each quantity with a starting value is considered a parameter, and the algorithm will adjust all the parameters looking for the best fit – i.e., the smallest MSE (and hence also the smallest SSE and RMSE).</li>
</ol>
</div>
<!-- end enumerate -->
<p>Let’s illustrate with an example.</p>
<div id="exm-balldrop" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.7 </strong></span>Returning to the ball dropping experiment, let’s fit <span id="eq-balldrop"><span class="math display">\[
\begin{aligned}
\texttt{time} &amp;= \alpha_0 + \alpha_1 \sqrt{\texttt{height}}
\end{aligned}
\tag{8.1}\]</span></span></p>
<p>using nonlinear least squares.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>nls.model <span class="ot">&lt;-</span> <span class="fu">nls</span>(time <span class="sc">~</span> alpha0 <span class="sc">+</span> alpha1 <span class="sc">*</span> <span class="fu">sqrt</span>(height), </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> BallDrop, </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">start =</span> <span class="fu">list</span>(<span class="at">alpha0 =</span> <span class="dv">0</span>, <span class="at">alpha1 =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>Notice how the model formula compares with the formula in (@eq-balldrop).
The starting point for the algorithm is specified with 
`start = list(alpha0 = 0, alpha1 = 1)`, which also declares 
the parameters to be fit.

We can obtain the coefficients of the fitted model with</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>nls.model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nonlinear regression model
  model: time ~ alpha0 + alpha1 * sqrt(height)
   data: BallDrop
 alpha0  alpha1 
0.01608 0.43080 
 residual sum-of-squares: 0.0007645

Number of iterations to convergence: 1 
Achieved convergence tolerance: 2.112e-07</code></pre>
</div>
</div>
<p>or</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(nls.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    alpha0     alpha1 
0.01607833 0.43080348 </code></pre>
</div>
</div>
<p>A more complete summary can be obtained by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nls.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Formula: time ~ alpha0 + alpha1 * sqrt(height)

Parameters:
       Estimate Std. Error t value Pr(&gt;|t|)    
alpha0 0.016078   0.004084   3.937 0.000498 ***
alpha1 0.430803   0.004863  88.580  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.005225 on 28 degrees of freedom

Number of iterations to convergence: 1 
Achieved convergence tolerance: 2.112e-07</code></pre>
</div>
</div>
<p>We can restrict our attention to the coefficients table with</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(nls.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Estimate  Std. Error   t value     Pr(&gt;|t|)
alpha0 0.01607833 0.004084015  3.936894 4.975519e-04
alpha1 0.43080348 0.004863416 88.580433 7.732182e-36</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(nls.model)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(time <span class="sc">~</span> height, <span class="at">data =</span> BallDrop) <span class="sc">|&gt;</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">f</span>(height) <span class="sc">~</span> height, <span class="at">color =</span> <span class="st">'gray40'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(nls.model) <span class="sc">~</span> <span class="fu">fitted</span>(nls.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>We can compare this to the ordinary least squares model by plotting both together on the same plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>lm.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> <span class="fu">sqrt</span>(height), <span class="at">data =</span> BallDrop)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(lm.model)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(time <span class="sc">~</span> height, <span class="at">data =</span> BallDrop) <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">f</span>(height) <span class="sc">~</span> height, <span class="at">color =</span> <span class="st">'gray80'</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">g</span>(height) <span class="sc">~</span> height, <span class="at">color =</span> <span class="st">'red'</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>In this particular case, there is very little difference between the two models, but this is not always the case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(nls.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    alpha0     alpha1 
0.01607833 0.43080348 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) sqrt(height) 
  0.01607833   0.43080348 </code></pre>
</div>
</div>
</div>
<!-- end example -->
<div id="exm-balldrop-again" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.8 </strong></span>Here is example where we fit a different model to the <code>BallDrop</code> data, namely <span class="math display">\[
    \texttt{time} = \alpha * \texttt{height}^p
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>power.model <span class="ot">&lt;-</span> <span class="fu">nls</span>(time <span class="sc">~</span> alpha <span class="sc">*</span> height<span class="sc">^</span>power, <span class="at">data =</span> BallDrop, </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">start =</span> <span class="fu">c</span>(<span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">power =</span> .<span class="dv">5</span>))</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(power.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Estimate  Std. Error   t value     Pr(&gt;|t|)
alpha 0.4472102 0.001342627 333.08590 6.333427e-52
power 0.4796679 0.005805313  82.62567 5.387914e-35</code></pre>
</div>
</div>
<p>A power law can also be fit using <code>lm()</code> by using a log-log transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>power.model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(time) <span class="sc">~</span> <span class="fu">log</span>(height), <span class="at">data =</span> BallDrop)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(power.model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate  Std. Error    t value     Pr(&gt;|t|)
(Intercept) -0.807610 0.004330482 -186.49426 7.101233e-45
log(height)  0.471911 0.006424548   73.45435 1.431476e-33</code></pre>
</div>
</div>
<p>Again, the parameter estimates (and uncertainties) are very similar. Recall that to compare our intercept in the second model to the <span class="math inline">\(\alpha\)</span> value in the first model, we must untransform:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(power.model2)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.4459225 </code></pre>
</div>
</div>
<p>We can use the delta method to estimate the uncertainty. Since <span class="math inline">\(\frac{d}{dx} e^x = e^x\)</span> the uncertainty is approximately <span class="math display">\[
0.4459225 \cdot 0.0043305
=
0.0019311
\]</span></p>
</div>
<!-- end example -->
<div id="exm-looking-at-residuals" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.9 </strong></span>In addition to comparing estimated parameters and their uncertainties, we should always look at the residuals of our model. For both the linear regression and the nonlinear least squares models, the assumption is that the error terms are independent, normally distributed, and have a common standard deviation. From the plots below we see</p>
<div class="enumerate">
<ol>
<li>The nonlinear least squares model is a better match for these assumptions than the linear regression model.</li>
<li>Both models reveal a lack of independence – at a given height, the residuals move up or down as a cluster as was discussed in the previous section. Neither model is designed to handle this flaw in the design of the experiment.</li>
</ol>
</div>
<!-- end enumerate -->
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(power.model), <span class="at">main =</span> <span class="st">"model 1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(power.model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(power.model) <span class="sc">~</span> <span class="fu">fitted</span>(power.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-35-3.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(power.model2) <span class="sc">~</span> <span class="fu">fitted</span>(power.model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-35-4.png" class="img-fluid" width="432"></p>
</div>
</div>
</div>
<!-- end example -->
<p>Now let’s take a look at an example where we need the extra flexibility of the nonlinear least squares approach.</p>
<div id="exm-hot-water" class="example theorem example">
<p><span class="theorem-title"><strong>Example 8.10 </strong></span>A professor at Macalester College put hot water in a mug and recorded the temperature as it cooled. Let’s see if we can fit a reasonable model to this data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(temp <span class="sc">~</span> time, <span class="at">data =</span> CoolingWater, <span class="at">ylab =</span> <span class="st">"temp (C)"</span>, <span class="at">xlab =</span> <span class="st">"time (sec)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Our first guess might be some sort of exponential decay</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>cooling.model1 <span class="ot">&lt;-</span> </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nls</span>(temp <span class="sc">~</span> A <span class="sc">*</span> <span class="fu">exp</span>( <span class="sc">-</span>k <span class="sc">*</span> time), <span class="at">data =</span> CoolingWater, </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">start =</span> <span class="fu">list</span>(<span class="at">A =</span> <span class="dv">100</span>, <span class="at">k =</span> <span class="fl">0.1</span>))</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>f1 <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(cooling.model1)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(temp <span class="sc">~</span> time, <span class="at">data =</span> CoolingWater, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">50</span>, <span class="dv">300</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">110</span>), </span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"temp (C)"</span>, <span class="at">xlab =</span> <span class="st">"time (sec)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_fun</span>(<span class="fu">f1</span>(time) <span class="sc">~</span> time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>That doesn’t fit very well, and there is a good reason. The model says that eventually the water will freeze because <span class="math display">\[
\lim_{t \to \infty} A e^{-k t} = 0
\]</span> when <span class="math inline">\(k &gt;0\)</span>. But clearly our water isn’t going to freeze sitting on a lab table. We can fix this by adding in an offset to account for the ambient temperature:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>cooling.model2 <span class="ot">&lt;-</span> <span class="fu">nls</span>(temp <span class="sc">~</span> ambient <span class="sc">+</span> A <span class="sc">*</span> <span class="fu">exp</span>(k <span class="sc">*</span> (<span class="dv">1</span><span class="sc">+</span>time)), <span class="at">data =</span> CoolingWater,</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">start =</span> <span class="fu">list</span>(<span class="at">ambient =</span> <span class="dv">20</span>, <span class="at">A =</span> <span class="dv">80</span>, <span class="at">k =</span> <span class="sc">-</span>.<span class="dv">1</span>) )</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>f2 <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(cooling.model2)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(temp <span class="sc">~</span> time, <span class="at">data =</span> CoolingWater, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">50</span>, <span class="dv">300</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">110</span>),</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"temp (C)"</span>, <span class="at">xlab =</span> <span class="st">"time (sec)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_fun</span>(<span class="fu">f1</span>(time) <span class="sc">~</span> time, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"gray80"</span>) <span class="sc">|&gt;</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_fun</span>(<span class="fu">f2</span>(time) <span class="sc">~</span> time, <span class="at">color =</span> <span class="st">"steelblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>This fits much better. Furthermore, this model can be derived from a differential equation <span class="math display">\[
\frac{dT}{dt} = -k (T_0 - T_{\mathrm{ambient}})
\;,
\]</span> known as Newton’s Law of Cooling.</p>
<p>Let’s take a look at the residual plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(cooling.model2) <span class="sc">~</span> time, <span class="at">data =</span> CoolingWater) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(cooling.model2, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>mplot() doesn't know how to handle this kind of input.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>use methods("mplot") to see a list of available methods.</code></pre>
</div>
</div>
<p>Hmm. These plots show a clear pattern and very little noise. The fit doesn’t look as good when viewed this way. It suggests that Newton’s Law of Cooling does not take into account all that is going on here. In particular, there is a considerable amount of evaporation (at least at the beginning when the water is warmer). More complicated models that take this into account can fit even better. For a discussion of a model that includes evaporation, see <a href="http://stanwagon.com/public/EvaporationPortmannWagonMiER.pdf" class="uri">http://stanwagon.com/public/EvaporationPortmannWagonMiER.pdf</a>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
<!-- end example -->
<section id="choosing-between-linear-and-non-linear-models" class="level3" data-number="8.8.1">
<h3 data-number="8.8.1" class="anchored" data-anchor-id="choosing-between-linear-and-non-linear-models"><span class="header-section-number">8.8.1</span> Choosing Between Linear and Non-linear Models</h3>
<p>So how do we choose between linear and non-linear models? Let’s enumerate some of the differences between them:</p>
<div class="enumerate">
<ol type="1">
<li><p>Some models cannot be expressed as linear models, even after transformations.</p>
<p>In this case we only have one option, the non-linear model.</p></li>
<li><p>Linear models can be fit quickly and accurately without numerical optimization algorithms because they satisfy nice linear algebra properties.</p>
<p>The use of numerical optimizers in non-linear least squares models makes them subject to potential problems with the optimizers. They may not converge, may converge to the wrong thing, or convergence may depend on choosing an appropriate starting point for the search.</p></li>
<li><p>The two types of models make different assumptions about the error terms.</p>
<p>In particular, when we apply transformations to achieve a linear model, those transformations often affect the distribution of the error terms as well. For example, if we apply a log-log transformation to fit a power law, then the model is</p>
<p><span class="math display">\[
\begin{aligned}
     \log( y ) &amp;= \beta_0 + \beta_1 \log(x) + \varepsilon
     \\
     y &amp;= e^{\beta_0}  x^{\beta_1} e^\varepsilon
     \\
     y &amp;= \alpha  x^{\beta_1} e^\varepsilon
\end{aligned}
\]</span></p>
<p>So the errors are multiplicative rather than additive and they have a normal distribution <em>after</em> applying the logarithmic transformation. This implies that the relative errors should be about the same magnitude rather than the absolute errors.</p>
<p>This is potentially very different from the nonlinear model where the errors are additive:</p>
<p><span class="math display">\[
     y = \alpha x^\beta + \varepsilon
\]</span></p>
<p>Plots of residuals vs.&nbsp;fits and qq-plots for residuals can help us diagnose whether the assumptions of a model are reasonable for a particular data set.</p></li>
<li><p>Linear models provide an easy way to produce confidence intervals for a mean response or an individual response.</p>
<p>The models fit using <code>nls()</code> do not have this capability.</p></li>
</ol>
</div>
<!-- end enumerate -->
</section>
</section>
<section id="exercises" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="exercises"><span class="header-section-number">8.9</span> Exercises</h2>
<div class="problem">
<p><strong>Ball drop, revisited</strong></p>
<p>In <a href="#exm-balldrop">Example&nbsp;<span>8.7</span></a>, we applied a square root transformation to the height. Is there another transformation that yields an even better fit?</p>
</div>
<!-- end problem -->
<div id="exr-soap" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.1 </strong></span><strong>Soap, revisited</strong></p>
<p>Remove the last few days from the <code>Soap</code> data set and refit the models in <a href="#exm-soap">Example&nbsp;<span>8.6</span></a>. How much do things change? Do the residuals look better, or is there still some cause for concern?</p>
</div>
<!-- end problem -->
<div id="exr-transformations" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.2 </strong></span><strong>Transformations</strong></p>
<p>For each of the following relationships between a response <span class="math inline">\(y\)</span> and an explanatory variable <span class="math inline">\(x\)</span>, if possible find a pair of transformations <span class="math inline">\(f\)</span> and <span class="math inline">\(g\)</span> so that <span class="math inline">\(g(y)\)</span> is a linear function of <span class="math inline">\(f(x)\)</span>: <span class="math display">\[
  g(y) = \beta_0 + \beta_1 f(x) \;.
\]</span> For example, if <span class="math inline">\(y = a e^{bx}\)</span>, then <span class="math inline">\(\log(y) = \log(a) + bx\)</span>, so <span class="math inline">\(g(y) = \log(y)\)</span>, <span class="math inline">\(f(x) = x\)</span>, <span class="math inline">\(\beta_0= \log(a)\)</span>, and <span class="math inline">\(\beta_1 = b\)</span>.</p>
<div class="columns">
<div class="column" style="width:50%;">
<ol type="a">
<li><span class="math inline">\(y = a b^x\)</span>.</li>
<li><span class="math inline">\(y = a x^b\)</span>.</li>
<li><span class="math inline">\(y = \frac{1}{a + bx}\)</span>.</li>
<li><span class="math inline">\(y = \frac{x}{a + bx}\)</span>.</li>
</ol>
</div><div class="column" style="width:50%;">
<ol start="5" type="a">
<li><span class="math inline">\(y = a x^2 + b x + c\)</span>.</li>
<li><span class="math inline">\(\displaystyle y = \frac{1}{1+e^{a+bx}}\)</span>.</li>
<li><span class="math inline">\(\displaystyle y = \frac{100}{1+e^{a+bx}}\)</span>.</li>
</ol>
</div>
</div>
</div>
<div class="mysolution">
<div class="enumerate">
<ol type="a">
<li><span class="math inline">\(\log(y) = \log(a) + x \log(b)\)</span>, so <span class="math inline">\(g(y) = \log(y)\)</span>, <span class="math inline">\(f(x) = x\)</span>, <span class="math inline">\(\beta_0 = \log(a)\)</span>, and <span class="math inline">\(\beta_1 = \log(b)\)</span>.</li>
<li><span class="math inline">\(\log(y) = \log(a) + b \log(x)\)</span>, so <span class="math inline">\(g(y) = \log(y)\)</span>, <span class="math inline">\(f(x) = \log(x)\)</span>, <span class="math inline">\(\beta_0 = \log(a)\)</span>, and <span class="math inline">\(\beta_1 = b\)</span>.</li>
<li><span class="math inline">\(\frac{1}{y} = a + b x\)</span>, so <span class="math inline">\(g(y) = \frac{1}{y}\)</span>, <span class="math inline">\(f(x) = x\)</span>, <span class="math inline">\(\beta_0 = a\)</span>, and <span class="math inline">\(\beta_1 = b\)</span>.</li>
<li><span class="math inline">\(\frac{1}{y} = \frac{a}{x} + b\)</span>, so <span class="math inline">\(g(y) = \frac{1}{y}\)</span>, <span class="math inline">\(f(x) = \frac{1}{x}\)</span>, <span class="math inline">\(\beta_0 = b\)</span>, and <span class="math inline">\(\beta_1 = a\)</span>.</li>
<li>not possible</li>
<li><span class="math inline">\(\frac{1}{y} = 1 + e^{a + bx}\)</span>, so <span class="math inline">\(\log(\frac{1}{y} - 1) = \log( \frac{1-y}{y} ) = {a + bx}\)</span>, so <span class="math inline">\(g(y) = \log(\frac{1-y}{y})\)</span>, <span class="math inline">\(f(x) = {x}\)</span>, <span class="math inline">\(\beta_0 = a\)</span>, and <span class="math inline">\(\beta_1 = b\)</span>.</li>
<li><span class="math inline">\(\frac{100}{y} = 1 + e^{a + bx}\)</span>, so <span class="math inline">\(\log(\frac{100}{y} - 1) = \log( \frac{100-y}{y} ) = {a + bx}\)</span>, so <span class="math inline">\(g(y) = \log(\frac{100-y}{y})\)</span>, <span class="math inline">\(f(x) = {x}\)</span>, <span class="math inline">\(\beta_0 = a\)</span>, and <span class="math inline">\(\beta_1 = b\)</span>.</li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end solution -->
<div class="problem">
<p><strong>Errors and transformations</strong> <!-- \probNote{Would make a good partial solution for students.}% --> What happens to the role of the error terms (<span class="math inline">\(\varepsilon\)</span>) when we transform the data? For each transformation from <a href="#exr-transformations">Exercise&nbsp;<span>8.2</span></a>, start with the form <span class="math display">\[
  g(y) = \beta_0 + \beta_1 f(x) + \varepsilon
\]</span> and transform back into a form involving the untransformed <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> to see how the error terms are involved in these transformed linear regression models.</p>
<p>It is important to remember that when we fit a linear model to transformed data, the usual assumptions of the model are that the errors in the (transformed) linear form are additive and normally distributed. The errors may appear differently in the untransformed relationship.</p>
</div>
<!-- end problem -->
<div id="exr-tukey-bulge-skew" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.3 </strong></span><strong>Tukey bulge and skew</strong></p>
<p>The transformations in the ladder of re-expression also affects the shape of a distribution.</p>
<div class="enumerate">
<ol type="a">
<li>If a distribution is symmetric, how does the shape change as we move up the ladder?</li>
<li>If a distribution is symmetric, how does the shape change as we move down the ladder?</li>
<li>If a distribution is left skewed, in what direction should we move to make the distribution more symmetric?</li>
<li>If a distribution is right skewed, in what direction should we move to make the distribution more symmetric?</li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<p>Moving up the ladder will spread the larger values more than the smaller values, resulting in a distribution that is right skewed.</p>
</div>
<!-- end solution -->
<div id="exr-pendulum" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.4 </strong></span><strong>Pendulum</strong></p>
<p>By attaching a heavy object to the end of a string, it is easy to construct pendulums of different lengths. Some physics students did this to see how the period (time in seconds until a pendulum returns to the same location) depends on the length (in meters) of the pendulum. The students constructed pendulums of lengths varying from <span class="math inline">\(10\)</span> cm to <span class="math inline">\(16\)</span> m and recorded the period length (averaged over several swings of the pendulum). The resulting data are in the <code>Pendulum</code> data set in the <strong><code>fastR2</code></strong> package.</p>
<div class="enumerate">
<ol type="a">
<li><p>Fit a power law to this data using a transformation and a linear model. How well does the power law fit? What is the estimated power in the power law based on this model?</p></li>
<li><p>Fit a power law to this data using a nonlinear model. How well does the power law fit? What is the estimated power in the power law based on this model?</p></li>
<li><p>Compare residual plots and normal-quantile plots for the residuals for the two models. How do the models compare in this regard?</p></li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<pre><code>At first glance, the two models might appear equally good.  In each case the 
power is a bit below 2 and the fits look good on top of the raw data. 
&lt;!--  (Note: the  --&gt;
&lt;!--  function produced by `makeFun()` does not know how to invert the log --&gt;
&lt;!--  transformation on the response variable, so we have to do that ourselves.) --&gt;</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(period) <span class="sc">~</span> <span class="fu">log</span>(length), <span class="at">data =</span> Pendulum)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">nls</span>(period <span class="sc">~</span> A <span class="sc">*</span> length<span class="sc">^</span>power, <span class="at">data =</span> Pendulum, <span class="at">start =</span> <span class="fu">list</span>(<span class="at">A =</span> <span class="dv">1</span>, <span class="at">power =</span> <span class="dv">2</span>))</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(model)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(model2)</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(period <span class="sc">~</span> length, <span class="at">data =</span> Pendulum) <span class="sc">|&gt;</span></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">f</span>(x) <span class="sc">~</span> x, <span class="at">col =</span> <span class="st">'gray50'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(period <span class="sc">~</span> length, <span class="at">data =</span> Pendulum) <span class="sc">|&gt;</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">g</span>(x) <span class="sc">~</span> x, <span class="at">col =</span> <span class="st">'red'</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-40-2.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate  Std. Error  t value     Pr(&gt;|t|)
(Intercept) 0.7207055 0.006360981 113.3010 2.027047e-35
log(length) 0.4784757 0.003937676 121.5122 3.536212e-36</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Estimate Std. Error  t value     Pr(&gt;|t|)
A     2.0469760 0.02202717 92.92961 2.843896e-33
power 0.4827226 0.00482899 99.96348 4.610858e-34</code></pre>
</div>
</div>
<pre><code>But if we look at the residuals, we see that the linear model is clearly 
better in this case.  The non-linear model suffers from heteroskedasticity.</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(model) <span class="sc">~</span> <span class="fu">fitted</span>(model)) <span class="sc">|&gt;</span> <span class="fu">gf_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(model2) <span class="sc">~</span> <span class="fu">fitted</span>(model2)) <span class="sc">|&gt;</span> <span class="fu">gf_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-41-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<pre><code>Both residual distributions are reasonably close to normal, but not perfect.
In the ordinary least squares model, the largets few residuals are not as large
as we would expect.</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>( <span class="sc">~</span> <span class="fu">resid</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-42-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<pre><code>The residuals in the non-linear model show a clear change 
in variance as the fitted value increases.  This is counteracted by the logarithmic
transformation of the explanatory variable.  (In other cases, the non-linaer model
might have the preferred residual distribution.)</code></pre>
<p>The estimated power based on the linear model is <span class="math inline">\(0.478 \pm 0.004\)</span>.</p>
</div>
<!-- end solution -->
<div id="exr-pressure" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.5 </strong></span><strong>Vapor pressure</strong></p>
<p>The <code>pressure</code> data set contains data on the relation between temperature in degrees Celsius and vapor pressure in millimeters (of mercury). With temperature as the predictor and pressure as the response, use transformations or nonlinear models as needed to obtain a good fit. Make a list of all the models you considered and explain how you chose your best model. What does your model say about the relationship between pressure and temperature?</p>
</div>
<!-- end problem -->
<div class="mysolution">
<p>Using Tukey’s buldge rules it is pretty easy to land at something like one of the following</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(pressure) <span class="sc">~</span> temperature, <span class="at">data =</span> pressure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(pressure) <span class="sc">~</span> <span class="fu">log</span>(temperature), <span class="at">data =</span> pressure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-43-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Neither of these is pefect (although both are much more linear than the original untransformed relationship). But if you think in degrees Kelvin instead, you might find a much better transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(pressure) <span class="sc">~</span> (<span class="fl">273.15</span> <span class="sc">+</span> temperature), <span class="at">data =</span> pressure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(pressure) <span class="sc">~</span> <span class="fu">log</span>(<span class="fl">273.15</span> <span class="sc">+</span> temperature), <span class="at">data =</span> pressure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-44-2.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(pressure) <span class="sc">~</span> <span class="dv">1</span><span class="sc">/</span>(<span class="fl">273.15</span> <span class="sc">+</span> temperature), <span class="at">data =</span> pressure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-44-3.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Ah, that last one looks quite good. Let’s try that one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(pressure) <span class="sc">~</span> <span class="fu">I</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="fl">273.15</span> <span class="sc">+</span> temperature)), <span class="at">data =</span> pressure)</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(model, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="432"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-45-2.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>Things still aren’t perfect. There’s a bit of a bow in the residual plot, but the size of the residuals is quite small relative to the scale of the log-of-pressure values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>( <span class="sc">~</span> <span class="fu">resid</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0745625  0.1517124</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>( <span class="sc">~</span> <span class="fu">log</span>(pressure), <span class="at">data =</span> pressure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -8.517193  6.692084</code></pre>
</div>
</div>
<p>Also the residual for the fourth observation is quite a bit larger than the rest.</p>
</div>
<!-- end solution -->
<div id="exr-cornit" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.6 </strong></span><strong>Fertilizing corn</strong></p>
<p>The <code>cornnit</code> data set in the package <strong><code>faraway</code></strong> contains data from a study investigating the relationship between corn yield (bushels per acre) and nitrogen (pounds per acre) fertilizer application in Wisconsin. Using nitrogen as the predictor and corn yield as the response, use transformations (if necessary) to obtain a good fit. Make a list of all the models you considered and explain how you chose your best model.</p>
</div>
<!-- end problem -->
<div id="exr-act-gpa" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.7 </strong></span><strong>ACT and GPA</strong></p>
<p>The data set <code>ACTgpa</code> (in the <strong><code>fastR2</code></strong> package) <!--   <http://www.calvin.edu/~stob/courses/m344/S07/data/actgpanona.csv> --> contains the ACT composite scores and GPAs of some randomly selected seniors at a Midwest liberal arts college.</p>
<div class="enumerate">
<ol type="a">
<li>Give a 95% confidence interval for the mean ACT score of seniors at this school.</li>
<li>Give a 95% confidence interval for the mean GPA of seniors at this school.</li>
<li>Use the data to estimate with 95% confidence the average GPA for all students who score 25 on the ACT.</li>
<li>Suppose you know a high school student who scored 30 on the ACT. Estimate with 95% confidence his GPA as a senior in college.</li>
<li>Are there any reasons to be concerned about the analyses you have just done? Explain.</li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->
<div class="mysolution">
<div class="enumerate">
<ol type="a">
<li><p>We can build a confidence interval for the mean by fitting a model with only an intercept term.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>grades <span class="ot">&lt;-</span> ACTgpa</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(ACT <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> grades))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               2.5 %   97.5 %
(Intercept) 24.24932 27.90453</code></pre>
</div>
</div>
<p>But this isn’t the only way to do it. Here are some other ways.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># here's another way to do it; but you don't need to know about it</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(grades<span class="sc">$</span>ACT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  grades$ACT
t = 29.386, df = 25, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 24.24932 27.90453
sample estimates:
mean of x 
 26.07692 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or you can do it by hand</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>x.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>( <span class="sc">~</span> ACT, <span class="at">data =</span> grades); x.bar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26.07692</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(grades); n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>t.star <span class="ot">&lt;-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> n<span class="dv">-1</span>); t.star</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.059539</code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sd</span>( <span class="sc">~</span> ACT, <span class="at">data =</span> grades) <span class="sc">/</span> <span class="fu">sqrt</span>(n); SE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.887387</code></pre>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>ME <span class="ot">&lt;-</span> t.star <span class="sc">*</span> SE; ME</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.827608</code></pre>
</div>
</div>
<pre><code>    So the CI is $26.0769231 \pm 1.8276077$.  Of course, that is too many digits, we 
    should do some rounding to
    $26.1 \pm 1.8$. </code></pre></li>
<li><p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(GPA <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> grades))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stdout} <code>2.5 %   97.5 %  (Intercept) 3.185408 3.578515</code> :::</p>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this could also be done the other ways shown above.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p></li>
<li><p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>grades.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(GPA <span class="sc">~</span> ACT, <span class="at">data =</span> grades)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(grades.model)</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(<span class="at">ACT =</span> <span class="dv">25</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stdout} <code>fit      lwr      upr  1 3.288243 3.166694 3.409792</code> ::: :::</p></li>
<li><p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(<span class="at">ACT =</span> <span class="dv">30</span>, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stdout} <code>fit      lwr      upr  1 3.723365 3.100775 4.345955</code> ::: :::</p></li>
<li><p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(GPA <span class="sc">~</span> ACT, <span class="at">data =</span> grades) <span class="sc">|&gt;</span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>(<span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>(<span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stderr} <code>Warning: Using the `size` aesthietic with geom_ribbon was deprecated in ggplot2 3.4.0.  ℹ Please use the `linewidth` aesthetic instead.</code> :::</p>
<p>::: {.cell-output-display} <img src="08-nonlinear_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="432"> :::</p>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(grades.model) <span class="sc">~</span> <span class="fu">fitted</span>(grades.model)) <span class="sc">|&gt;</span> </span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stderr} <code>`geom_smooth()` using method = 'loess'</code> :::</p>
<p>::: {.cell-output-display} <img src="08-nonlinear_files/figure-html/unnamed-chunk-51-2.png" class="img-fluid" width="432"> ::: :::</p>
<pre><code>     There are no major concerns with the regression model. The
     residuals look pretty good.  (There is perhaps a bit more variability
     in GPA for the lower ACT scores and if you said you were worried about
     that, I would not argue.) 

     The prediction intervals are very wide and hardly useful, however.
     It's pretty hard to give a precise estimate for an individual
     person -- there's just too much variability from preson to person, 
     even among people with the same ACT score. </code></pre></li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end solution -->
<div id="exr-drag1" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.8 </strong></span><strong>Drag force</strong></p>
<p>In the absence of air resistance, a dropped object will continue to accelerate as it falls. But if there is air resistance, the situation is different. The drag force due to air resistance depends on the velocity of an object and operates in the opposite direction of motion. Thus as the object’s velocity increases, so does the drag force until it eventually equals the force due to gravity. At this point the net force is <span class="math inline">\(0\)</span> and the object ceases to accelerate, remaining at a constant velocity called the terminal velocity.</p>
<p>Now consider the following experiment to determine how terminal velocity depends on the mass (and therefore on the downward force of gravity) of the falling object. A helium balloon is rigged with a small basket and just the right ballast to make it neutrally buoyant. Mass is then added and the terminal velocity is calculated by measuring the time it takes to fall between two sensors once terminal velocity has been reached.</p>
<p>The <code>Drag</code> data set (in the <strong><code>fastR2</code></strong> package) contains the results of such an experiment conducted by some undergraduate physics students. Mass is measured in grams and velocity in meters per second. (The distance between the two sensors used for determining terminal velocity is given in the <code>height</code> variable.)</p>
<p>By fitting models to this data, determine which of the following “drag laws” matches the data best:</p>
<div class="itemize">
<ol type="a">
<li>Drag is proportional to velocity.</li>
<li>Drag is proportional to the square of velocity.</li>
<li>Drag is proportional to the square root of velocity.</li>
<li>Drag is proportional to the logarithm of velocity.</li>
</ol>
</div>
<!-- end itemize -->
</div>
<!-- end problem -->
<div class="mysolution">
<p>The best of these four models is a model that says drag is proportional to the square of velocity. Given the design of the experiment, it makes the most sense to fit velocity as a function of drag force. Here are several ways we could do the fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(velocity<span class="sc">^</span><span class="dv">2</span> <span class="sc">~</span> force.drag, <span class="at">data =</span> Drag)</span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(velocity <span class="sc">~</span> <span class="fu">sqrt</span>(force.drag), <span class="at">data =</span> Drag)</span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(velocity) <span class="sc">~</span> <span class="fu">log</span>(force.drag), <span class="at">data =</span> Drag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error    t value     Pr(&gt;|t|)
(Intercept) -0.06227051 0.221930683 -0.2805854 7.804746e-01
force.drag   0.08399767 0.002320596 36.1965958 3.448978e-32</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept)      -0.03585585 0.054832417 -0.653917 5.169073e-01
sqrt(force.drag)  0.29097916 0.006806886 42.747762 5.239126e-35</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)     -1.1622713 0.04539588 -25.60301 2.020737e-26
log(force.drag)  0.4744661 0.01241003  38.23248 4.103776e-33</code></pre>
</div>
</div>
<p>Note that <code>model1</code>, <code>model2</code>, and <code>model3</code> are not equivalent, but they all tell roughly the same story.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>f1 <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(model1)</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>f2 <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(model2)</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>f3 <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(model3)</span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(velocity <span class="sc">~</span> force.drag, <span class="at">data =</span> Drag) <span class="sc">|&gt;</span></span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">sqrt</span>(<span class="fu">f1</span>(x)) <span class="sc">~</span> x, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb145-6"><a href="#cb145-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">f2</span>(x) <span class="sc">~</span> x, <span class="at">alpha =</span> .<span class="dv">4</span>, <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">|&gt;</span></span>
<span id="cb145-7"><a href="#cb145-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fun</span>(<span class="fu">f3</span>(x) <span class="sc">~</span> x, <span class="at">alpha =</span> .<span class="dv">4</span>, <span class="at">color =</span> <span class="st">'brown'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="432"></p>
</div>
</div>
<p>The fit for these models reveals some potential errors in the design of this experiment. Separating out the data by the height used to determine velocity suggests that perhaps some of the velocity measurements are not yet at terminal velocity. In both groups, the velocities for the greatest drag forces are not as fast as the pattern of the remaining data would lead us to expect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(velocity<span class="sc">^</span><span class="dv">2</span> <span class="sc">~</span> force.drag, <span class="at">data =</span> Drag, <span class="at">color =</span> <span class="sc">~</span> height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/drag-plots-1.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(model1, <span class="at">w =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/drag-plots-2.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(velocity) <span class="sc">~</span> <span class="fu">log</span>(force.drag), <span class="at">data =</span> Drag, <span class="at">color =</span> <span class="sc">~</span> height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/drag-plots-3.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(velocity <span class="sc">~</span> force.drag, <span class="at">data =</span> Drag, <span class="at">color =</span> <span class="sc">~</span> height) <span class="sc">|&gt;</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_x_log10</span>(), <span class="fu">scale_y_log10</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/drag-plots-4.png" class="img-fluid" width="432"></p>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mplot</span>(model3, <span class="at">w =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-nonlinear_files/figure-html/drag-plots-5.png" class="img-fluid" width="432"></p>
</div>
</div>
</div>
<!-- end solution -->
<div id="exr-drag-problems" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.9 </strong></span><strong>Drag force, revisited</strong></p>
<p>Construct a plot that reveals a likely systematic problem with the <code>Drag</code> (see <a href="#exr-drag1">Exercise&nbsp;<span>8.8</span></a>) data set. Speculate about a potential cause for this.</p>
</div>
<!-- end problem -->
<div class="mysolution">
<p>See previous problem.</p>
</div>
<!-- end solution -->
<div id="exr-drag-subset" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.10 </strong></span><strong>Drag force, subsetting the data</strong></p>
<p><a href="#exr-drag-problems">Exercise&nbsp;<span>8.9</span></a> suggests that some of the data should be removed before analyzing the <code>Drag</code> data set. Redo <a href="#exr-drag1">Exercise&nbsp;<span>8.8</span></a> after removing this data.</p>
</div>
<!-- end problem -->
<div id="exr-spheres-1" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.11 </strong></span><strong>Spheres</strong></p>
<p>The <code>Spheres</code> data set (in the <strong><code>fastR2</code></strong> package) contains measurements of the diameter (in meters) and mass (in kilograms) of a set of steel ball bearings. We would expect the mass to be proportional to the cube of the diameter. Fit a model and see if the data reflect this.</p>
</div>
<!-- end problem -->
<div id="exr-spheres-2" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.12 </strong></span><strong>More spheres</strong></p>
<p>The <code>Spheres</code> data set (in the <strong><code>fastR2</code></strong> package) contains measurements of the diameter (in meters) and mass (in kilograms) of a set of steel ball bearings. We would expect the mass to be proportional to the cube of the diameter. Using appropriate transformations fit two models: one that predicts mass from diameter and one that predicts diameter from mass. How do the two models compare?</p>
</div>
<!-- end problem -->
<div id="exr-utilities-therms-by-temp" class="problem theorem exercise">
<p><span class="theorem-title"><strong>Exercise 8.13 </strong></span><strong>Utilities</strong></p>
<p>The <code>Utilities</code> data set has information from utilities bills at a Minnesota residence. Fit a linear model that predicts <code>thermsPerDay</code> from <code>temp</code>.</p>
<div class="enumerate">
<ol type="a">
<li>What observations should you remove from the data before doing the analysis? Why?</li>
<li>Are any transformations needed?</li>
<li>How happy are you with the fit of your model? Are there any reasons for concern?</li>
<li>Interpret your final model (even if it is with some reservations listed in part c). What does it say about the relationship between average monthly temperature and the amount of gas used at this residence? What do the parameters represent?</li>
</ol>
</div>
<!-- end enumerate -->
</div>
<!-- end problem -->


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Mosteller:1977:DataAnalysis" class="csl-entry" role="doc-biblioentry">
Mosteller, F., and J. Tukey. 1977. <em>Data Analysis and Regression</em>. Addison-Wesley.
</div>
<div id="ref-Tukey:1977:EDA" class="csl-entry" role="doc-biblioentry">
Tukey, John W. 1977. <em>Exploratory Data Analysis</em>. pub-aw:adr: pub-aw.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>For now, it suffices to know that larger values of <span class="math inline">\(r^2\)</span> generally indicate a better fit. We will discuss <span class="math inline">\(r^2\)</span> and what it measures <a href="10-more-examples.html#sec-r-squared"><span>Section&nbsp;10.3</span></a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p> The model with evaporation adds another complication in that the resulting differential equation cannot be solved algebraically, so there is no algebraic formula to fit with <code>nls()</code>. But the method of least squares can still be used by creating a parameterized numerical function that computes the sum of squares and using a numerical minimizer to find the optimal parameter values. Since the use of numerical differential equation solvers is a bit beyond the scope of this course, we’ll leave that discussion for another day.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-simple-linear.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-hypothesis-testing.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>