project:
  type: book
  output-dir: _site
  preview:
    port: 4300
  
format:
  html:
    include-in-header: macros.qmd
    theme: cosmo
    code-copy: true
    toc: true
    toc-location: right
    df-print: paged
    fig-height: 2.5
    fig-width: 4.5
    fig-align: center
  pdf: 
    include-in-header: macros.tex
    geometry: 
      - "margin=0.9in"

css: book.css

tbl-cap-location: bottom

filters: 
  - latex-environment
  
environments:
  - center: center
  - problem: exercise
  
commands: 
  - blue: blue

book:
  title: "Statistics for the Physical Sciences and Engineering"
  output-file: "Pruim-Stat-for-Phys-Sci-and-Engr"
  author: "Randall Pruim"
  date: last_modified
  favicon: cover.png
  search: true
  downloads: [pdf]
  sidebar: 
    style: docked
  chapters:
    - index.qmd
    - 00-chap0.qmd
    - 01-graphical.qmd
    - 02-numerical.qmd
    - 03-probability.qmd
    - 04-random-variables.qmd
    - 05-transformations.qmd
    - 06-propagation.qmd
    - 07-simple-linear.qmd
    - 08-nonlinear.qmd
    - 09-hypothesis-testing.qmd
    - 10-more-examples.qmd
    - references.qmd

bibliography: ['bibtex/R.bib', 'bibtex/DataSets.bib', 'bibtex/StatsBook.bib']
