project:
  type: book
  output-dir: _book
  preview:
    port: 4300
  
execute:
  freeze: auto
  
format:
  html:
    theme: cosmo
    code-copy: true
    toc: true
    toc-location: right
    df-print: paged
    fig-height: 2.5
    fig-width: 4.5
    fig-align: center

css: book.css

tbl-cap-location: bottom

filters: 
  - latex-environment
  
environments:
  - center: center
  - problem: exercise
  
commands: 
  - blue: blue

book:
  title: "Statistics for the Physical Sciences and Engineering"
  author: "Randall Pruim"
  date: last_modified
  favicon: cover.png
  search: true
  downloads: [epub, pdf]
  sidebar: 
    style: docked
  chapters:
    - index.qmd
    - Stat241-Chap0.qmd
    - Stat241-Graphical.qmd
    - Stat241-Numerical.qmd
    - Stat241-Probability.qmd
    - Stat241-RandomVariables.qmd
    - Stat241-Transformations.qmd
    - Stat241-Propagation.qmd
    - Stat241-SimpleLinear.qmd
    - Stat241-NonLinear.qmd
    - Stat241-HypothesisTesting.qmd
    - Stat241-MoreExamples.qmd
    - references.qmd

bibliography: ['bibtex/R.bib', 'bibtex/DataSets.bib', 'bibtex/StatsBook.bib']
